/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignTripDto,
  CancelAssignmentDto,
  CancelAssignmentResponseEntity,
  CreateTripDto,
  NotifyStepDto,
  PublicTripActionResponseEntity,
  PublicTripEntity,
  TripActionResponseEntity,
  TripEntity,
  TripsControllerGetPublicParams,
  TripsControllerListParams,
  UpdateTripDto,
  UpdateTripResponseEntity
} from '../../model';

import { fetcher } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getTripsControllerListUrl = (params?: TripsControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/trips?${stringifiedParams}` : `/api/trips`
}

export const tripsControllerList = async (params?: TripsControllerListParams, options?: Parameters<typeof fetcher>[1]): Promise<TripEntity[]> => {

  return fetcher<TripEntity[]>(getTripsControllerListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getTripsControllerListQueryKey = (params?: TripsControllerListParams,) => {
    return [
    `/api/trips`, ...(params ? [params] : [])
    ] as const;
    }


export const getTripsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof tripsControllerList>>, TError = unknown>(params?: TripsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tripsControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTripsControllerListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof tripsControllerList>>> = ({ signal }) => tripsControllerList(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tripsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TripsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof tripsControllerList>>>
export type TripsControllerListQueryError = unknown


export function useTripsControllerList<TData = Awaited<ReturnType<typeof tripsControllerList>>, TError = unknown>(
 params: undefined |  TripsControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof tripsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tripsControllerList>>,
          TError,
          Awaited<ReturnType<typeof tripsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTripsControllerList<TData = Awaited<ReturnType<typeof tripsControllerList>>, TError = unknown>(
 params?: TripsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tripsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tripsControllerList>>,
          TError,
          Awaited<ReturnType<typeof tripsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTripsControllerList<TData = Awaited<ReturnType<typeof tripsControllerList>>, TError = unknown>(
 params?: TripsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tripsControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTripsControllerList<TData = Awaited<ReturnType<typeof tripsControllerList>>, TError = unknown>(
 params?: TripsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tripsControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTripsControllerListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getTripsControllerCreateUrl = () => {




  return `/api/trips`
}

export const tripsControllerCreate = async (createTripDto: CreateTripDto, options?: Parameters<typeof fetcher>[1]): Promise<TripEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<TripEntity>(getTripsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createTripDto)
  }
);}





export const getTripsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerCreate>>, TError,TripsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof tripsControllerCreate>>, TError,TripsControllerCreateMutationVariables, TContext> => {

const mutationKey = ['tripsControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tripsControllerCreate>>, TripsControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  tripsControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TripsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof tripsControllerCreate>>>
    export type TripsControllerCreateMutationBody = CreateTripDto
    export type TripsControllerCreateMutationError = unknown
    export type TripsControllerCreateMutationVariables = {data: CreateTripDto}

    export const useTripsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerCreate>>, TError,TripsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tripsControllerCreate>>,
        TError,
        TripsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getTripsControllerCreateMutationOptions(options), queryClient);
    }
    export const getTripsControllerGetPublicUrl = (ref: string,
    params?: TripsControllerGetPublicParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/trips/${ref}?${stringifiedParams}` : `/api/trips/${ref}`
}

export const tripsControllerGetPublic = async (ref: string,
    params?: TripsControllerGetPublicParams, options?: Parameters<typeof fetcher>[1]): Promise<PublicTripEntity> => {

  return fetcher<PublicTripEntity>(getTripsControllerGetPublicUrl(ref,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getTripsControllerGetPublicQueryKey = (ref: string,
    params?: TripsControllerGetPublicParams,) => {
    return [
    `/api/trips/${ref}`, ...(params ? [params] : [])
    ] as const;
    }


export const getTripsControllerGetPublicQueryOptions = <TData = Awaited<ReturnType<typeof tripsControllerGetPublic>>, TError = unknown>(ref: string,
    params?: TripsControllerGetPublicParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tripsControllerGetPublic>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTripsControllerGetPublicQueryKey(ref,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof tripsControllerGetPublic>>> = ({ signal }) => tripsControllerGetPublic(ref,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: ref !== null && ref !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tripsControllerGetPublic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TripsControllerGetPublicQueryResult = NonNullable<Awaited<ReturnType<typeof tripsControllerGetPublic>>>
export type TripsControllerGetPublicQueryError = unknown


export function useTripsControllerGetPublic<TData = Awaited<ReturnType<typeof tripsControllerGetPublic>>, TError = unknown>(
 ref: string,
    params: undefined |  TripsControllerGetPublicParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof tripsControllerGetPublic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tripsControllerGetPublic>>,
          TError,
          Awaited<ReturnType<typeof tripsControllerGetPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTripsControllerGetPublic<TData = Awaited<ReturnType<typeof tripsControllerGetPublic>>, TError = unknown>(
 ref: string,
    params?: TripsControllerGetPublicParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tripsControllerGetPublic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tripsControllerGetPublic>>,
          TError,
          Awaited<ReturnType<typeof tripsControllerGetPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTripsControllerGetPublic<TData = Awaited<ReturnType<typeof tripsControllerGetPublic>>, TError = unknown>(
 ref: string,
    params?: TripsControllerGetPublicParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tripsControllerGetPublic>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTripsControllerGetPublic<TData = Awaited<ReturnType<typeof tripsControllerGetPublic>>, TError = unknown>(
 ref: string,
    params?: TripsControllerGetPublicParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tripsControllerGetPublic>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTripsControllerGetPublicQueryOptions(ref,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getTripsControllerUpdateUrl = (ref: string,) => {




  return `/api/trips/${ref}`
}

export const tripsControllerUpdate = async (ref: string,
    updateTripDto: UpdateTripDto, options?: Parameters<typeof fetcher>[1]): Promise<UpdateTripResponseEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<UpdateTripResponseEntity>(getTripsControllerUpdateUrl(ref),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateTripDto)
  }
);}





export const getTripsControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerUpdate>>, TError,TripsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof tripsControllerUpdate>>, TError,TripsControllerUpdateMutationVariables, TContext> => {

const mutationKey = ['tripsControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tripsControllerUpdate>>, TripsControllerUpdateMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  tripsControllerUpdate(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TripsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof tripsControllerUpdate>>>
    export type TripsControllerUpdateMutationBody = UpdateTripDto
    export type TripsControllerUpdateMutationError = unknown
    export type TripsControllerUpdateMutationVariables = {ref: string;data: UpdateTripDto}

    export const useTripsControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerUpdate>>, TError,TripsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tripsControllerUpdate>>,
        TError,
        TripsControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getTripsControllerUpdateMutationOptions(options), queryClient);
    }
    export const getTripsControllerAssignUrl = (ref: string,) => {




  return `/api/trips/${ref}/assign`
}

export const tripsControllerAssign = async (ref: string,
    assignTripDto: AssignTripDto, options?: Parameters<typeof fetcher>[1]): Promise<UpdateTripResponseEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<UpdateTripResponseEntity>(getTripsControllerAssignUrl(ref),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(assignTripDto)
  }
);}





export const getTripsControllerAssignMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerAssign>>, TError,TripsControllerAssignMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof tripsControllerAssign>>, TError,TripsControllerAssignMutationVariables, TContext> => {

const mutationKey = ['tripsControllerAssign'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tripsControllerAssign>>, TripsControllerAssignMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  tripsControllerAssign(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TripsControllerAssignMutationResult = NonNullable<Awaited<ReturnType<typeof tripsControllerAssign>>>
    export type TripsControllerAssignMutationBody = AssignTripDto
    export type TripsControllerAssignMutationError = unknown
    export type TripsControllerAssignMutationVariables = {ref: string;data: AssignTripDto}

    export const useTripsControllerAssign = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerAssign>>, TError,TripsControllerAssignMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tripsControllerAssign>>,
        TError,
        TripsControllerAssignMutationVariables,
        TContext
      > => {
      return useMutation(getTripsControllerAssignMutationOptions(options), queryClient);
    }
    export const getTripsControllerCancelAssignmentUrl = (ref: string,) => {




  return `/api/trips/${ref}/cancel-assignment`
}

export const tripsControllerCancelAssignment = async (ref: string,
    cancelAssignmentDto: CancelAssignmentDto, options?: Parameters<typeof fetcher>[1]): Promise<CancelAssignmentResponseEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<CancelAssignmentResponseEntity>(getTripsControllerCancelAssignmentUrl(ref),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(cancelAssignmentDto)
  }
);}





export const getTripsControllerCancelAssignmentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerCancelAssignment>>, TError,TripsControllerCancelAssignmentMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof tripsControllerCancelAssignment>>, TError,TripsControllerCancelAssignmentMutationVariables, TContext> => {

const mutationKey = ['tripsControllerCancelAssignment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tripsControllerCancelAssignment>>, TripsControllerCancelAssignmentMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  tripsControllerCancelAssignment(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TripsControllerCancelAssignmentMutationResult = NonNullable<Awaited<ReturnType<typeof tripsControllerCancelAssignment>>>
    export type TripsControllerCancelAssignmentMutationBody = CancelAssignmentDto
    export type TripsControllerCancelAssignmentMutationError = unknown
    export type TripsControllerCancelAssignmentMutationVariables = {ref: string;data: CancelAssignmentDto}

    export const useTripsControllerCancelAssignment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerCancelAssignment>>, TError,TripsControllerCancelAssignmentMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tripsControllerCancelAssignment>>,
        TError,
        TripsControllerCancelAssignmentMutationVariables,
        TContext
      > => {
      return useMutation(getTripsControllerCancelAssignmentMutationOptions(options), queryClient);
    }
    export const getTripsControllerAdvanceStepUrl = (ref: string,) => {




  return `/api/trips/${ref}/advance-step`
}

export const tripsControllerAdvanceStep = async (ref: string, options?: Parameters<typeof fetcher>[1]): Promise<TripActionResponseEntity> => {

  return fetcher<TripActionResponseEntity>(getTripsControllerAdvanceStepUrl(ref),
  {
    ...options,
    method: 'POST'


  }
);}





export const getTripsControllerAdvanceStepMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerAdvanceStep>>, TError,TripsControllerAdvanceStepMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof tripsControllerAdvanceStep>>, TError,TripsControllerAdvanceStepMutationVariables, TContext> => {

const mutationKey = ['tripsControllerAdvanceStep'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tripsControllerAdvanceStep>>, TripsControllerAdvanceStepMutationVariables> = (props) => {
          const {ref} = props ?? {};

          return  tripsControllerAdvanceStep(ref,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TripsControllerAdvanceStepMutationResult = NonNullable<Awaited<ReturnType<typeof tripsControllerAdvanceStep>>>

    export type TripsControllerAdvanceStepMutationError = unknown
    export type TripsControllerAdvanceStepMutationVariables = {ref: string}

    export const useTripsControllerAdvanceStep = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerAdvanceStep>>, TError,TripsControllerAdvanceStepMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tripsControllerAdvanceStep>>,
        TError,
        TripsControllerAdvanceStepMutationVariables,
        TContext
      > => {
      return useMutation(getTripsControllerAdvanceStepMutationOptions(options), queryClient);
    }
    export const getTripsControllerNotifyUrl = (ref: string,) => {




  return `/api/trips/${ref}/notify`
}

export const tripsControllerNotify = async (ref: string,
    notifyStepDto: NotifyStepDto, options?: Parameters<typeof fetcher>[1]): Promise<PublicTripActionResponseEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<PublicTripActionResponseEntity>(getTripsControllerNotifyUrl(ref),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(notifyStepDto)
  }
);}





export const getTripsControllerNotifyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerNotify>>, TError,TripsControllerNotifyMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof tripsControllerNotify>>, TError,TripsControllerNotifyMutationVariables, TContext> => {

const mutationKey = ['tripsControllerNotify'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tripsControllerNotify>>, TripsControllerNotifyMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  tripsControllerNotify(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TripsControllerNotifyMutationResult = NonNullable<Awaited<ReturnType<typeof tripsControllerNotify>>>
    export type TripsControllerNotifyMutationBody = NotifyStepDto
    export type TripsControllerNotifyMutationError = unknown
    export type TripsControllerNotifyMutationVariables = {ref: string;data: NotifyStepDto}

    export const useTripsControllerNotify = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerNotify>>, TError,TripsControllerNotifyMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tripsControllerNotify>>,
        TError,
        TripsControllerNotifyMutationVariables,
        TContext
      > => {
      return useMutation(getTripsControllerNotifyMutationOptions(options), queryClient);
    }
    export const getTripsControllerDispatchDriverUrl = (ref: string,) => {




  return `/api/trips/${ref}/dispatch-driver`
}

export const tripsControllerDispatchDriver = async (ref: string, options?: Parameters<typeof fetcher>[1]): Promise<TripEntity> => {

  return fetcher<TripEntity>(getTripsControllerDispatchDriverUrl(ref),
  {
    ...options,
    method: 'POST'


  }
);}





export const getTripsControllerDispatchDriverMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerDispatchDriver>>, TError,TripsControllerDispatchDriverMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof tripsControllerDispatchDriver>>, TError,TripsControllerDispatchDriverMutationVariables, TContext> => {

const mutationKey = ['tripsControllerDispatchDriver'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tripsControllerDispatchDriver>>, TripsControllerDispatchDriverMutationVariables> = (props) => {
          const {ref} = props ?? {};

          return  tripsControllerDispatchDriver(ref,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TripsControllerDispatchDriverMutationResult = NonNullable<Awaited<ReturnType<typeof tripsControllerDispatchDriver>>>

    export type TripsControllerDispatchDriverMutationError = unknown
    export type TripsControllerDispatchDriverMutationVariables = {ref: string}

    export const useTripsControllerDispatchDriver = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerDispatchDriver>>, TError,TripsControllerDispatchDriverMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tripsControllerDispatchDriver>>,
        TError,
        TripsControllerDispatchDriverMutationVariables,
        TContext
      > => {
      return useMutation(getTripsControllerDispatchDriverMutationOptions(options), queryClient);
    }
    export const getTripsControllerUploadNameboardUrl = (ref: string,) => {




  return `/api/trips/${ref}/nameboard`
}

export const tripsControllerUploadNameboard = async (ref: string, options?: Parameters<typeof fetcher>[1]): Promise<TripEntity> => {

  return fetcher<TripEntity>(getTripsControllerUploadNameboardUrl(ref),
  {
    ...options,
    method: 'POST'


  }
);}





export const getTripsControllerUploadNameboardMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerUploadNameboard>>, TError,TripsControllerUploadNameboardMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof tripsControllerUploadNameboard>>, TError,TripsControllerUploadNameboardMutationVariables, TContext> => {

const mutationKey = ['tripsControllerUploadNameboard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tripsControllerUploadNameboard>>, TripsControllerUploadNameboardMutationVariables> = (props) => {
          const {ref} = props ?? {};

          return  tripsControllerUploadNameboard(ref,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TripsControllerUploadNameboardMutationResult = NonNullable<Awaited<ReturnType<typeof tripsControllerUploadNameboard>>>

    export type TripsControllerUploadNameboardMutationError = unknown
    export type TripsControllerUploadNameboardMutationVariables = {ref: string}

    export const useTripsControllerUploadNameboard = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tripsControllerUploadNameboard>>, TError,TripsControllerUploadNameboardMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tripsControllerUploadNameboard>>,
        TError,
        TripsControllerUploadNameboardMutationVariables,
        TContext
      > => {
      return useMutation(getTripsControllerUploadNameboardMutationOptions(options), queryClient);
    }
