// Ported verbatim from the legacy suivi-chauffeur-twilio/server.js catalogues.
// Do not hand-edit values here without checking docs/LEGACY_FEATURES.md §6.
export interface CountryDef {
  name: string;
  code: string;
  // Missing for Côte d'Ivoire ('CI') — a genuine gap in the legacy data, kept as-is.
  dial?: string;
  tz: string;
  currency: string;
}

export const COUNTRIES: CountryDef[] = [
  {
    name: 'Afghanistan',
    code: 'AF',
    dial: '+93',
    tz: 'Asia/Kabul',
    currency: 'AFN',
  },
  {
    name: 'South Africa',
    code: 'ZA',
    dial: '+27',
    tz: 'Africa/Johannesburg',
    currency: 'ZAR',
  },
  {
    name: 'Albania',
    code: 'AL',
    dial: '+355',
    tz: 'Europe/Tirane',
    currency: 'ALL',
  },
  {
    name: 'Algeria',
    code: 'DZ',
    dial: '+213',
    tz: 'Africa/Algiers',
    currency: 'DZD',
  },
  {
    name: 'Germany',
    code: 'DE',
    dial: '+49',
    tz: 'Europe/Berlin',
    currency: 'EUR',
  },
  {
    name: 'Andorra',
    code: 'AD',
    dial: '+376',
    tz: 'Europe/Andorra',
    currency: 'EUR',
  },
  {
    name: 'Angola',
    code: 'AO',
    dial: '+244',
    tz: 'Africa/Luanda',
    currency: 'AOA',
  },
  {
    name: 'Antigua and Barbuda',
    code: 'AG',
    dial: '+1268',
    tz: 'America/Antigua',
    currency: 'XCD',
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    dial: '+966',
    tz: 'Asia/Riyadh',
    currency: 'SAR',
  },
  {
    name: 'Argentina',
    code: 'AR',
    dial: '+54',
    tz: 'America/Argentina/Buenos_Aires',
    currency: 'ARS',
  },
  {
    name: 'Armenia',
    code: 'AM',
    dial: '+374',
    tz: 'Asia/Yerevan',
    currency: 'AMD',
  },
  {
    name: 'Australia (Sydney)',
    code: 'AU-NSW',
    dial: '+61',
    tz: 'Australia/Sydney',
    currency: 'AUD',
  },
  {
    name: 'Australia (Perth)',
    code: 'AU-WA',
    dial: '+61',
    tz: 'Australia/Perth',
    currency: 'AUD',
  },
  {
    name: 'Austria',
    code: 'AT',
    dial: '+43',
    tz: 'Europe/Vienna',
    currency: 'EUR',
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    dial: '+994',
    tz: 'Asia/Baku',
    currency: 'AZN',
  },
  {
    name: 'Bahamas',
    code: 'BS',
    dial: '+1242',
    tz: 'America/Nassau',
    currency: 'BSD',
  },
  {
    name: 'Bahrain',
    code: 'BH',
    dial: '+973',
    tz: 'Asia/Bahrain',
    currency: 'BHD',
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    dial: '+880',
    tz: 'Asia/Dhaka',
    currency: 'BDT',
  },
  {
    name: 'Barbados',
    code: 'BB',
    dial: '+1246',
    tz: 'America/Barbados',
    currency: 'BBD',
  },
  {
    name: 'Belgium',
    code: 'BE',
    dial: '+32',
    tz: 'Europe/Brussels',
    currency: 'EUR',
  },
  {
    name: 'Belize',
    code: 'BZ',
    dial: '+501',
    tz: 'America/Belize',
    currency: 'BZD',
  },
  {
    name: 'Benin',
    code: 'BJ',
    dial: '+229',
    tz: 'Africa/Porto-Novo',
    currency: 'XOF',
  },
  {
    name: 'Bhutan',
    code: 'BT',
    dial: '+975',
    tz: 'Asia/Thimphu',
    currency: 'BTN',
  },
  {
    name: 'Belarus',
    code: 'BY',
    dial: '+375',
    tz: 'Europe/Minsk',
    currency: 'BYN',
  },
  {
    name: 'Myanmar (Burma)',
    code: 'MM',
    dial: '+95',
    tz: 'Asia/Yangon',
    currency: 'MMK',
  },
  {
    name: 'Bolivia',
    code: 'BO',
    dial: '+591',
    tz: 'America/La_Paz',
    currency: 'BOB',
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    dial: '+387',
    tz: 'Europe/Sarajevo',
    currency: 'BAM',
  },
  {
    name: 'Botswana',
    code: 'BW',
    dial: '+267',
    tz: 'Africa/Gaborone',
    currency: 'BWP',
  },
  {
    name: 'Brazil (São Paulo)',
    code: 'BR-SP',
    dial: '+55',
    tz: 'America/Sao_Paulo',
    currency: 'BRL',
  },
  {
    name: 'Brazil (Manaus)',
    code: 'BR-AM',
    dial: '+55',
    tz: 'America/Manaus',
    currency: 'BRL',
  },
  {
    name: 'Brunei',
    code: 'BN',
    dial: '+673',
    tz: 'Asia/Brunei',
    currency: 'BND',
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    dial: '+359',
    tz: 'Europe/Sofia',
    currency: 'BGN',
  },
  {
    name: 'Burkina Faso',
    code: 'BF',
    dial: '+226',
    tz: 'Africa/Ouagadougou',
    currency: 'XOF',
  },
  {
    name: 'Burundi',
    code: 'BI',
    dial: '+257',
    tz: 'Africa/Bujumbura',
    currency: 'BIF',
  },
  {
    name: 'Cambodia',
    code: 'KH',
    dial: '+855',
    tz: 'Asia/Phnom_Penh',
    currency: 'KHR',
  },
  {
    name: 'Cameroon',
    code: 'CM',
    dial: '+237',
    tz: 'Africa/Douala',
    currency: 'XAF',
  },
  {
    name: 'Canada (Toronto)',
    code: 'CA-ON',
    dial: '+1',
    tz: 'America/Toronto',
    currency: 'CAD',
  },
  {
    name: 'Canada (Vancouver)',
    code: 'CA-BC',
    dial: '+1',
    tz: 'America/Vancouver',
    currency: 'CAD',
  },
  {
    name: 'Cabo Verde',
    code: 'CV',
    dial: '+238',
    tz: 'Atlantic/Cape_Verde',
    currency: 'CVE',
  },
  {
    name: 'Chile',
    code: 'CL',
    dial: '+56',
    tz: 'America/Santiago',
    currency: 'CLP',
  },
  {
    name: 'China (Beijing/Shanghai)',
    code: 'CN',
    dial: '+86',
    tz: 'Asia/Shanghai',
    currency: 'CNY',
  },
  {
    name: 'Cyprus',
    code: 'CY',
    dial: '+357',
    tz: 'Asia/Nicosia',
    currency: 'EUR',
  },
  {
    name: 'Colombia',
    code: 'CO',
    dial: '+57',
    tz: 'America/Bogota',
    currency: 'COP',
  },
  {
    name: 'Comoros',
    code: 'KM',
    dial: '+269',
    tz: 'Indian/Comoro',
    currency: 'KMF',
  },
  {
    name: 'Congo (Brazzaville)',
    code: 'CG',
    dial: '+242',
    tz: 'Africa/Brazzaville',
    currency: 'XAF',
  },
  {
    name: 'DR Congo (Kinshasa)',
    code: 'CD',
    dial: '+243',
    tz: 'Africa/Kinshasa',
    currency: 'CDF',
  },
  {
    name: 'North Korea',
    code: 'KP',
    dial: '+850',
    tz: 'Asia/Pyongyang',
    currency: 'KPW',
  },
  {
    name: 'South Korea',
    code: 'KR',
    dial: '+82',
    tz: 'Asia/Seoul',
    currency: 'KRW',
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    dial: '+506',
    tz: 'America/Costa_Rica',
    currency: 'CRC',
  },
  {
    name: "Côte d'Ivoire (Ivory Coast)",
    code: 'CI',
    tz: 'Africa/Abidjan',
    currency: 'XOF',
  },
  {
    name: 'Croatia',
    code: 'HR',
    dial: '+385',
    tz: 'Europe/Zagreb',
    currency: 'EUR',
  },
  {
    name: 'Cuba',
    code: 'CU',
    dial: '+53',
    tz: 'America/Havana',
    currency: 'CUP',
  },
  {
    name: 'Denmark',
    code: 'DK',
    dial: '+45',
    tz: 'Europe/Copenhagen',
    currency: 'DKK',
  },
  {
    name: 'Djibouti',
    code: 'DJ',
    dial: '+253',
    tz: 'Africa/Djibouti',
    currency: 'DJF',
  },
  {
    name: 'Dominica',
    code: 'DM',
    dial: '+1767',
    tz: 'America/Dominica',
    currency: 'XCD',
  },
  {
    name: 'Egypt',
    code: 'EG',
    dial: '+20',
    tz: 'Africa/Cairo',
    currency: 'EGP',
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    dial: '+971',
    tz: 'Asia/Dubai',
    currency: 'AED',
  },
  {
    name: 'Ecuador',
    code: 'EC',
    dial: '+593',
    tz: 'America/Guayaquil',
    currency: 'USD',
  },
  {
    name: 'Eritrea',
    code: 'ER',
    dial: '+291',
    tz: 'Africa/Asmara',
    currency: 'ERN',
  },
  {
    name: 'Spain',
    code: 'ES',
    dial: '+34',
    tz: 'Europe/Madrid',
    currency: 'EUR',
  },
  {
    name: 'Estonia',
    code: 'EE',
    dial: '+372',
    tz: 'Europe/Tallinn',
    currency: 'EUR',
  },
  {
    name: 'Eswatini',
    code: 'SZ',
    dial: '+268',
    tz: 'Africa/Mbabane',
    currency: 'SZL',
  },
  {
    name: 'United States (New York)',
    code: 'US-NY',
    dial: '+1',
    tz: 'America/New_York',
    currency: 'USD',
  },
  {
    name: 'United States (Chicago)',
    code: 'US-IL',
    dial: '+1',
    tz: 'America/Chicago',
    currency: 'USD',
  },
  {
    name: 'United States (Denver)',
    code: 'US-CO',
    dial: '+1',
    tz: 'America/Denver',
    currency: 'USD',
  },
  {
    name: 'United States (Los Angeles)',
    code: 'US-CA',
    dial: '+1',
    tz: 'America/Los_Angeles',
    currency: 'USD',
  },
  {
    name: 'United States (Anchorage)',
    code: 'US-AK',
    dial: '+1',
    tz: 'America/Anchorage',
    currency: 'USD',
  },
  {
    name: 'United States (Hawaii)',
    code: 'US-HI',
    dial: '+1',
    tz: 'Pacific/Honolulu',
    currency: 'USD',
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    dial: '+251',
    tz: 'Africa/Addis_Ababa',
    currency: 'ETB',
  },
  {
    name: 'Fiji',
    code: 'FJ',
    dial: '+679',
    tz: 'Pacific/Fiji',
    currency: 'FJD',
  },
  {
    name: 'Finland',
    code: 'FI',
    dial: '+358',
    tz: 'Europe/Helsinki',
    currency: 'EUR',
  },
  {
    name: 'France',
    code: 'FR',
    dial: '+33',
    tz: 'Europe/Paris',
    currency: 'EUR',
  },
  {
    name: 'Gabon',
    code: 'GA',
    dial: '+241',
    tz: 'Africa/Libreville',
    currency: 'XAF',
  },
  {
    name: 'Gambia',
    code: 'GM',
    dial: '+220',
    tz: 'Africa/Banjul',
    currency: 'GMD',
  },
  {
    name: 'Georgia',
    code: 'GE',
    dial: '+995',
    tz: 'Asia/Tbilisi',
    currency: 'GEL',
  },
  {
    name: 'Ghana',
    code: 'GH',
    dial: '+233',
    tz: 'Africa/Accra',
    currency: 'GHS',
  },
  {
    name: 'Greece',
    code: 'GR',
    dial: '+30',
    tz: 'Europe/Athens',
    currency: 'EUR',
  },
  {
    name: 'Grenada',
    code: 'GD',
    dial: '+1473',
    tz: 'America/Grenada',
    currency: 'XCD',
  },
  {
    name: 'Guatemala',
    code: 'GT',
    dial: '+502',
    tz: 'America/Guatemala',
    currency: 'GTQ',
  },
  {
    name: 'Guinea',
    code: 'GN',
    dial: '+224',
    tz: 'Africa/Conakry',
    currency: 'GNF',
  },
  {
    name: 'Guinea-Bissau',
    code: 'GW',
    dial: '+245',
    tz: 'Africa/Bissau',
    currency: 'XOF',
  },
  {
    name: 'Equatorial Guinea',
    code: 'GQ',
    dial: '+240',
    tz: 'Africa/Malabo',
    currency: 'XAF',
  },
  {
    name: 'Guyana',
    code: 'GY',
    dial: '+592',
    tz: 'America/Guyana',
    currency: 'GYD',
  },
  {
    name: 'Haiti',
    code: 'HT',
    dial: '+509',
    tz: 'America/Port-au-Prince',
    currency: 'HTG',
  },
  {
    name: 'Honduras',
    code: 'HN',
    dial: '+504',
    tz: 'America/Tegucigalpa',
    currency: 'HNL',
  },
  {
    name: 'Hong Kong',
    code: 'HK',
    dial: '+852',
    tz: 'Asia/Hong_Kong',
    currency: 'HKD',
  },
  {
    name: 'Hungary',
    code: 'HU',
    dial: '+36',
    tz: 'Europe/Budapest',
    currency: 'HUF',
  },
  {
    name: 'Marshall Islands',
    code: 'MH',
    dial: '+692',
    tz: 'Pacific/Majuro',
    currency: 'USD',
  },
  {
    name: 'Solomon Islands',
    code: 'SB',
    dial: '+677',
    tz: 'Pacific/Guadalcanal',
    currency: 'SBD',
  },
  {
    name: 'India',
    code: 'IN',
    dial: '+91',
    tz: 'Asia/Kolkata',
    currency: 'INR',
  },
  {
    name: 'Indonesia (Jakarta)',
    code: 'ID',
    dial: '+62',
    tz: 'Asia/Jakarta',
    currency: 'IDR',
  },
  {
    name: 'Iraq',
    code: 'IQ',
    dial: '+964',
    tz: 'Asia/Baghdad',
    currency: 'IQD',
  },
  {
    name: 'Iran',
    code: 'IR',
    dial: '+98',
    tz: 'Asia/Tehran',
    currency: 'IRR',
  },
  {
    name: 'Ireland',
    code: 'IE',
    dial: '+353',
    tz: 'Europe/Dublin',
    currency: 'EUR',
  },
  {
    name: 'Iceland',
    code: 'IS',
    dial: '+354',
    tz: 'Atlantic/Reykjavik',
    currency: 'ISK',
  },
  {
    name: 'Israel',
    code: 'IL',
    dial: '+972',
    tz: 'Asia/Jerusalem',
    currency: 'ILS',
  },
  {
    name: 'Italy',
    code: 'IT',
    dial: '+39',
    tz: 'Europe/Rome',
    currency: 'EUR',
  },
  {
    name: 'Jamaica',
    code: 'JM',
    dial: '+1876',
    tz: 'America/Jamaica',
    currency: 'JMD',
  },
  {
    name: 'Japan',
    code: 'JP',
    dial: '+81',
    tz: 'Asia/Tokyo',
    currency: 'JPY',
  },
  {
    name: 'Jordan',
    code: 'JO',
    dial: '+962',
    tz: 'Asia/Amman',
    currency: 'JOD',
  },
  {
    name: 'Kazakhstan',
    code: 'KZ',
    dial: '+7',
    tz: 'Asia/Almaty',
    currency: 'KZT',
  },
  {
    name: 'Kenya',
    code: 'KE',
    dial: '+254',
    tz: 'Africa/Nairobi',
    currency: 'KES',
  },
  {
    name: 'Kyrgyzstan',
    code: 'KG',
    dial: '+996',
    tz: 'Asia/Bishkek',
    currency: 'KGS',
  },
  {
    name: 'Kiribati',
    code: 'KI',
    dial: '+686',
    tz: 'Pacific/Tarawa',
    currency: 'AUD',
  },
  {
    name: 'Kosovo',
    code: 'XK',
    dial: '+383',
    tz: 'Europe/Belgrade',
    currency: 'EUR',
  },
  {
    name: 'Kuwait',
    code: 'KW',
    dial: '+965',
    tz: 'Asia/Kuwait',
    currency: 'KWD',
  },
  {
    name: 'Laos',
    code: 'LA',
    dial: '+856',
    tz: 'Asia/Vientiane',
    currency: 'LAK',
  },
  {
    name: 'Lesotho',
    code: 'LS',
    dial: '+266',
    tz: 'Africa/Maseru',
    currency: 'LSL',
  },
  {
    name: 'Latvia',
    code: 'LV',
    dial: '+371',
    tz: 'Europe/Riga',
    currency: 'EUR',
  },
  {
    name: 'Lebanon',
    code: 'LB',
    dial: '+961',
    tz: 'Asia/Beirut',
    currency: 'LBP',
  },
  {
    name: 'Liberia',
    code: 'LR',
    dial: '+231',
    tz: 'Africa/Monrovia',
    currency: 'LRD',
  },
  {
    name: 'Libya',
    code: 'LY',
    dial: '+218',
    tz: 'Africa/Tripoli',
    currency: 'LYD',
  },
  {
    name: 'Liechtenstein',
    code: 'LI',
    dial: '+423',
    tz: 'Europe/Vaduz',
    currency: 'CHF',
  },
  {
    name: 'Lithuania',
    code: 'LT',
    dial: '+370',
    tz: 'Europe/Vilnius',
    currency: 'EUR',
  },
  {
    name: 'Luxembourg',
    code: 'LU',
    dial: '+352',
    tz: 'Europe/Luxembourg',
    currency: 'EUR',
  },
  {
    name: 'Macao',
    code: 'MO',
    dial: '+853',
    tz: 'Asia/Macau',
    currency: 'MOP',
  },
  {
    name: 'North Macedonia',
    code: 'MK',
    dial: '+389',
    tz: 'Europe/Skopje',
    currency: 'MKD',
  },
  {
    name: 'Madagascar',
    code: 'MG',
    dial: '+261',
    tz: 'Indian/Antananarivo',
    currency: 'MGA',
  },
  {
    name: 'Malaysia',
    code: 'MY',
    dial: '+60',
    tz: 'Asia/Kuala_Lumpur',
    currency: 'MYR',
  },
  {
    name: 'Malawi',
    code: 'MW',
    dial: '+265',
    tz: 'Africa/Blantyre',
    currency: 'MWK',
  },
  {
    name: 'Maldives',
    code: 'MV',
    dial: '+960',
    tz: 'Indian/Maldives',
    currency: 'MVR',
  },
  {
    name: 'Mali',
    code: 'ML',
    dial: '+223',
    tz: 'Africa/Bamako',
    currency: 'XOF',
  },
  {
    name: 'Malta',
    code: 'MT',
    dial: '+356',
    tz: 'Europe/Malta',
    currency: 'EUR',
  },
  {
    name: 'Morocco',
    code: 'MA',
    dial: '+212',
    tz: 'Africa/Casablanca',
    currency: 'MAD',
  },
  {
    name: 'Mauritius',
    code: 'MU',
    dial: '+230',
    tz: 'Indian/Mauritius',
    currency: 'MUR',
  },
  {
    name: 'Mauritania',
    code: 'MR',
    dial: '+222',
    tz: 'Africa/Nouakchott',
    currency: 'MRU',
  },
  {
    name: 'Mexico',
    code: 'MX',
    dial: '+52',
    tz: 'America/Mexico_City',
    currency: 'MXN',
  },
  {
    name: 'Micronesia',
    code: 'FM',
    dial: '+691',
    tz: 'Pacific/Chuuk',
    currency: 'USD',
  },
  {
    name: 'Moldova',
    code: 'MD',
    dial: '+373',
    tz: 'Europe/Chisinau',
    currency: 'MDL',
  },
  {
    name: 'Monaco',
    code: 'MC',
    dial: '+377',
    tz: 'Europe/Monaco',
    currency: 'EUR',
  },
  {
    name: 'Mongolia',
    code: 'MN',
    dial: '+976',
    tz: 'Asia/Ulaanbaatar',
    currency: 'MNT',
  },
  {
    name: 'Montenegro',
    code: 'ME',
    dial: '+382',
    tz: 'Europe/Podgorica',
    currency: 'EUR',
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    dial: '+258',
    tz: 'Africa/Maputo',
    currency: 'MZN',
  },
  {
    name: 'Namibia',
    code: 'NA',
    dial: '+264',
    tz: 'Africa/Windhoek',
    currency: 'NAD',
  },
  {
    name: 'Nauru',
    code: 'NR',
    dial: '+674',
    tz: 'Pacific/Nauru',
    currency: 'AUD',
  },
  {
    name: 'Nepal',
    code: 'NP',
    dial: '+977',
    tz: 'Asia/Kathmandu',
    currency: 'NPR',
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    dial: '+505',
    tz: 'America/Managua',
    currency: 'NIO',
  },
  {
    name: 'Niger',
    code: 'NE',
    dial: '+227',
    tz: 'Africa/Niamey',
    currency: 'XOF',
  },
  {
    name: 'Nigeria',
    code: 'NG',
    dial: '+234',
    tz: 'Africa/Lagos',
    currency: 'NGN',
  },
  {
    name: 'Norway',
    code: 'NO',
    dial: '+47',
    tz: 'Europe/Oslo',
    currency: 'NOK',
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    dial: '+64',
    tz: 'Pacific/Auckland',
    currency: 'NZD',
  },
  {
    name: 'Oman',
    code: 'OM',
    dial: '+968',
    tz: 'Asia/Muscat',
    currency: 'OMR',
  },
  {
    name: 'Uganda',
    code: 'UG',
    dial: '+256',
    tz: 'Africa/Kampala',
    currency: 'UGX',
  },
  {
    name: 'Uzbekistan',
    code: 'UZ',
    dial: '+998',
    tz: 'Asia/Tashkent',
    currency: 'UZS',
  },
  {
    name: 'Pakistan',
    code: 'PK',
    dial: '+92',
    tz: 'Asia/Karachi',
    currency: 'PKR',
  },
  {
    name: 'Palau',
    code: 'PW',
    dial: '+680',
    tz: 'Pacific/Palau',
    currency: 'USD',
  },
  {
    name: 'Palestine',
    code: 'PS',
    dial: '+970',
    tz: 'Asia/Gaza',
    currency: 'ILS',
  },
  {
    name: 'Panama',
    code: 'PA',
    dial: '+507',
    tz: 'America/Panama',
    currency: 'PAB',
  },
  {
    name: 'Papua New Guinea',
    code: 'PG',
    dial: '+675',
    tz: 'Pacific/Port_Moresby',
    currency: 'PGK',
  },
  {
    name: 'Paraguay',
    code: 'PY',
    dial: '+595',
    tz: 'America/Asuncion',
    currency: 'PYG',
  },
  {
    name: 'Netherlands',
    code: 'NL',
    dial: '+31',
    tz: 'Europe/Amsterdam',
    currency: 'EUR',
  },
  {
    name: 'Peru',
    code: 'PE',
    dial: '+51',
    tz: 'America/Lima',
    currency: 'PEN',
  },
  {
    name: 'Philippines',
    code: 'PH',
    dial: '+63',
    tz: 'Asia/Manila',
    currency: 'PHP',
  },
  {
    name: 'Poland',
    code: 'PL',
    dial: '+48',
    tz: 'Europe/Warsaw',
    currency: 'PLN',
  },
  {
    name: 'Portugal',
    code: 'PT',
    dial: '+351',
    tz: 'Europe/Lisbon',
    currency: 'EUR',
  },
  {
    name: 'Qatar',
    code: 'QA',
    dial: '+974',
    tz: 'Asia/Qatar',
    currency: 'QAR',
  },
  {
    name: 'Central African Republic',
    code: 'CF',
    dial: '+236',
    tz: 'Africa/Bangui',
    currency: 'XAF',
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    dial: '+1809',
    tz: 'America/Santo_Domingo',
    currency: 'DOP',
  },
  {
    name: 'Czechia',
    code: 'CZ',
    dial: '+420',
    tz: 'Europe/Prague',
    currency: 'CZK',
  },
  {
    name: 'Romania',
    code: 'RO',
    dial: '+40',
    tz: 'Europe/Bucharest',
    currency: 'RON',
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    dial: '+44',
    tz: 'Europe/London',
    currency: 'GBP',
  },
  {
    name: 'Russia (Moscow)',
    code: 'RU-MOW',
    dial: '+7',
    tz: 'Europe/Moscow',
    currency: 'RUB',
  },
  {
    name: 'Russia (Yekaterinburg)',
    code: 'RU-SVE',
    dial: '+7',
    tz: 'Asia/Yekaterinburg',
    currency: 'RUB',
  },
  {
    name: 'Russia (Novosibirsk)',
    code: 'RU-NVS',
    dial: '+7',
    tz: 'Asia/Novosibirsk',
    currency: 'RUB',
  },
  {
    name: 'Russia (Vladivostok)',
    code: 'RU-PRI',
    dial: '+7',
    tz: 'Asia/Vladivostok',
    currency: 'RUB',
  },
  {
    name: 'Rwanda',
    code: 'RW',
    dial: '+250',
    tz: 'Africa/Kigali',
    currency: 'RWF',
  },
  {
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    dial: '+1869',
    tz: 'America/St_Kitts',
    currency: 'XCD',
  },
  {
    name: 'San Marino',
    code: 'SM',
    dial: '+378',
    tz: 'Europe/San_Marino',
    currency: 'EUR',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    dial: '+1784',
    tz: 'America/St_Vincent',
    currency: 'XCD',
  },
  {
    name: 'Saint Lucia',
    code: 'LC',
    dial: '+1758',
    tz: 'America/St_Lucia',
    currency: 'XCD',
  },
  {
    name: 'El Salvador',
    code: 'SV',
    dial: '+503',
    tz: 'America/El_Salvador',
    currency: 'USD',
  },
  {
    name: 'Samoa',
    code: 'WS',
    dial: '+685',
    tz: 'Pacific/Apia',
    currency: 'WST',
  },
  {
    name: 'São Tomé and Príncipe',
    code: 'ST',
    dial: '+239',
    tz: 'Africa/Sao_Tome',
    currency: 'STN',
  },
  {
    name: 'Senegal',
    code: 'SN',
    dial: '+221',
    tz: 'Africa/Dakar',
    currency: 'XOF',
  },
  {
    name: 'Serbia',
    code: 'RS',
    dial: '+381',
    tz: 'Europe/Belgrade',
    currency: 'RSD',
  },
  {
    name: 'Seychelles',
    code: 'SC',
    dial: '+248',
    tz: 'Indian/Mahe',
    currency: 'SCR',
  },
  {
    name: 'Sierra Leone',
    code: 'SL',
    dial: '+232',
    tz: 'Africa/Freetown',
    currency: 'SLE',
  },
  {
    name: 'Singapore',
    code: 'SG',
    dial: '+65',
    tz: 'Asia/Singapore',
    currency: 'SGD',
  },
  {
    name: 'Slovakia',
    code: 'SK',
    dial: '+421',
    tz: 'Europe/Bratislava',
    currency: 'EUR',
  },
  {
    name: 'Slovenia',
    code: 'SI',
    dial: '+386',
    tz: 'Europe/Ljubljana',
    currency: 'EUR',
  },
  {
    name: 'Somalia',
    code: 'SO',
    dial: '+252',
    tz: 'Africa/Mogadishu',
    currency: 'SOS',
  },
  {
    name: 'Sudan',
    code: 'SD',
    dial: '+249',
    tz: 'Africa/Khartoum',
    currency: 'SDG',
  },
  {
    name: 'South Sudan',
    code: 'SS',
    dial: '+211',
    tz: 'Africa/Juba',
    currency: 'SSP',
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    dial: '+94',
    tz: 'Asia/Colombo',
    currency: 'LKR',
  },
  {
    name: 'Sweden',
    code: 'SE',
    dial: '+46',
    tz: 'Europe/Stockholm',
    currency: 'SEK',
  },
  {
    name: 'Switzerland',
    code: 'CH',
    dial: '+41',
    tz: 'Europe/Zurich',
    currency: 'CHF',
  },
  {
    name: 'Suriname',
    code: 'SR',
    dial: '+597',
    tz: 'America/Paramaribo',
    currency: 'SRD',
  },
  {
    name: 'Syria',
    code: 'SY',
    dial: '+963',
    tz: 'Asia/Damascus',
    currency: 'SYP',
  },
  {
    name: 'Tajikistan',
    code: 'TJ',
    dial: '+992',
    tz: 'Asia/Dushanbe',
    currency: 'TJS',
  },
  {
    name: 'Taiwan',
    code: 'TW',
    dial: '+886',
    tz: 'Asia/Taipei',
    currency: 'TWD',
  },
  {
    name: 'Tanzania',
    code: 'TZ',
    dial: '+255',
    tz: 'Africa/Dar_es_Salaam',
    currency: 'TZS',
  },
  {
    name: 'Chad',
    code: 'TD',
    dial: '+235',
    tz: 'Africa/Ndjamena',
    currency: 'XAF',
  },
  {
    name: 'Thailand',
    code: 'TH',
    dial: '+66',
    tz: 'Asia/Bangkok',
    currency: 'THB',
  },
  {
    name: 'Timor-Leste',
    code: 'TL',
    dial: '+670',
    tz: 'Asia/Dili',
    currency: 'USD',
  },
  {
    name: 'Togo',
    code: 'TG',
    dial: '+228',
    tz: 'Africa/Lome',
    currency: 'XOF',
  },
  {
    name: 'Tonga',
    code: 'TO',
    dial: '+676',
    tz: 'Pacific/Tongatapu',
    currency: 'TOP',
  },
  {
    name: 'Trinidad and Tobago',
    code: 'TT',
    dial: '+1868',
    tz: 'America/Port_of_Spain',
    currency: 'TTD',
  },
  {
    name: 'Tunisia',
    code: 'TN',
    dial: '+216',
    tz: 'Africa/Tunis',
    currency: 'TND',
  },
  {
    name: 'Turkmenistan',
    code: 'TM',
    dial: '+993',
    tz: 'Asia/Ashgabat',
    currency: 'TMT',
  },
  {
    name: 'Turkey (Türkiye)',
    code: 'TR',
    dial: '+90',
    tz: 'Europe/Istanbul',
    currency: 'TRY',
  },
  {
    name: 'Tuvalu',
    code: 'TV',
    dial: '+688',
    tz: 'Pacific/Funafuti',
    currency: 'AUD',
  },
  {
    name: 'Ukraine',
    code: 'UA',
    dial: '+380',
    tz: 'Europe/Kyiv',
    currency: 'UAH',
  },
  {
    name: 'Uruguay',
    code: 'UY',
    dial: '+598',
    tz: 'America/Montevideo',
    currency: 'UYU',
  },
  {
    name: 'Vanuatu',
    code: 'VU',
    dial: '+678',
    tz: 'Pacific/Efate',
    currency: 'VUV',
  },
  {
    name: 'Vatican City',
    code: 'VA',
    dial: '+39',
    tz: 'Europe/Vatican',
    currency: 'EUR',
  },
  {
    name: 'Venezuela',
    code: 'VE',
    dial: '+58',
    tz: 'America/Caracas',
    currency: 'VES',
  },
  {
    name: 'Vietnam',
    code: 'VN',
    dial: '+84',
    tz: 'Asia/Ho_Chi_Minh',
    currency: 'VND',
  },
  {
    name: 'Yemen',
    code: 'YE',
    dial: '+967',
    tz: 'Asia/Aden',
    currency: 'YER',
  },
  {
    name: 'Zambia',
    code: 'ZM',
    dial: '+260',
    tz: 'Africa/Lusaka',
    currency: 'ZMW',
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    dial: '+263',
    tz: 'Africa/Harare',
    currency: 'USD',
  },
];
