/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateVehicleTypeDto,
  OkResponseEntity,
  SetActiveDto,
  UpdateVehicleTypeDto,
  VehicleTypeEntity
} from '../../model';

import { fetcher } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getVehicleTypesControllerListUrl = () => {




  return `/api/vehicles`
}

export const vehicleTypesControllerList = async ( options?: Parameters<typeof fetcher>[1]): Promise<VehicleTypeEntity[]> => {

  return fetcher<VehicleTypeEntity[]>(getVehicleTypesControllerListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getVehicleTypesControllerListQueryKey = () => {
    return [
    `/api/vehicles`
    ] as const;
    }


export const getVehicleTypesControllerListQueryOptions = <TData = Awaited<ReturnType<typeof vehicleTypesControllerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehicleTypesControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVehicleTypesControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof vehicleTypesControllerList>>> = ({ signal }) => vehicleTypesControllerList({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof vehicleTypesControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VehicleTypesControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof vehicleTypesControllerList>>>
export type VehicleTypesControllerListQueryError = unknown


export function useVehicleTypesControllerList<TData = Awaited<ReturnType<typeof vehicleTypesControllerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehicleTypesControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof vehicleTypesControllerList>>,
          TError,
          Awaited<ReturnType<typeof vehicleTypesControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVehicleTypesControllerList<TData = Awaited<ReturnType<typeof vehicleTypesControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehicleTypesControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof vehicleTypesControllerList>>,
          TError,
          Awaited<ReturnType<typeof vehicleTypesControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVehicleTypesControllerList<TData = Awaited<ReturnType<typeof vehicleTypesControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehicleTypesControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useVehicleTypesControllerList<TData = Awaited<ReturnType<typeof vehicleTypesControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehicleTypesControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVehicleTypesControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getVehicleTypesControllerCreateUrl = () => {




  return `/api/vehicles`
}

export const vehicleTypesControllerCreate = async (createVehicleTypeDto: CreateVehicleTypeDto, options?: Parameters<typeof fetcher>[1]): Promise<VehicleTypeEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<VehicleTypeEntity>(getVehicleTypesControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createVehicleTypeDto)
  }
);}





export const getVehicleTypesControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehicleTypesControllerCreate>>, TError,VehicleTypesControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof vehicleTypesControllerCreate>>, TError,VehicleTypesControllerCreateMutationVariables, TContext> => {

const mutationKey = ['vehicleTypesControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof vehicleTypesControllerCreate>>, VehicleTypesControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  vehicleTypesControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VehicleTypesControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof vehicleTypesControllerCreate>>>
    export type VehicleTypesControllerCreateMutationBody = CreateVehicleTypeDto
    export type VehicleTypesControllerCreateMutationError = unknown
    export type VehicleTypesControllerCreateMutationVariables = {data: CreateVehicleTypeDto}

    export const useVehicleTypesControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehicleTypesControllerCreate>>, TError,VehicleTypesControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof vehicleTypesControllerCreate>>,
        TError,
        VehicleTypesControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getVehicleTypesControllerCreateMutationOptions(options), queryClient);
    }
    export const getVehicleTypesControllerUpdateUrl = (ref: string,) => {




  return `/api/vehicles/${ref}`
}

export const vehicleTypesControllerUpdate = async (ref: string,
    updateVehicleTypeDto: UpdateVehicleTypeDto, options?: Parameters<typeof fetcher>[1]): Promise<VehicleTypeEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<VehicleTypeEntity>(getVehicleTypesControllerUpdateUrl(ref),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateVehicleTypeDto)
  }
);}





export const getVehicleTypesControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehicleTypesControllerUpdate>>, TError,VehicleTypesControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof vehicleTypesControllerUpdate>>, TError,VehicleTypesControllerUpdateMutationVariables, TContext> => {

const mutationKey = ['vehicleTypesControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof vehicleTypesControllerUpdate>>, VehicleTypesControllerUpdateMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  vehicleTypesControllerUpdate(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VehicleTypesControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof vehicleTypesControllerUpdate>>>
    export type VehicleTypesControllerUpdateMutationBody = UpdateVehicleTypeDto
    export type VehicleTypesControllerUpdateMutationError = unknown
    export type VehicleTypesControllerUpdateMutationVariables = {ref: string;data: UpdateVehicleTypeDto}

    export const useVehicleTypesControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehicleTypesControllerUpdate>>, TError,VehicleTypesControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof vehicleTypesControllerUpdate>>,
        TError,
        VehicleTypesControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getVehicleTypesControllerUpdateMutationOptions(options), queryClient);
    }
    export const getVehicleTypesControllerDeleteUrl = (ref: string,) => {




  return `/api/vehicles/${ref}`
}

export const vehicleTypesControllerDelete = async (ref: string, options?: Parameters<typeof fetcher>[1]): Promise<OkResponseEntity> => {

  return fetcher<OkResponseEntity>(getVehicleTypesControllerDeleteUrl(ref),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getVehicleTypesControllerDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehicleTypesControllerDelete>>, TError,VehicleTypesControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof vehicleTypesControllerDelete>>, TError,VehicleTypesControllerDeleteMutationVariables, TContext> => {

const mutationKey = ['vehicleTypesControllerDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof vehicleTypesControllerDelete>>, VehicleTypesControllerDeleteMutationVariables> = (props) => {
          const {ref} = props ?? {};

          return  vehicleTypesControllerDelete(ref,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VehicleTypesControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof vehicleTypesControllerDelete>>>

    export type VehicleTypesControllerDeleteMutationError = unknown
    export type VehicleTypesControllerDeleteMutationVariables = {ref: string}

    export const useVehicleTypesControllerDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehicleTypesControllerDelete>>, TError,VehicleTypesControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof vehicleTypesControllerDelete>>,
        TError,
        VehicleTypesControllerDeleteMutationVariables,
        TContext
      > => {
      return useMutation(getVehicleTypesControllerDeleteMutationOptions(options), queryClient);
    }
    export const getVehicleTypesControllerSetActiveUrl = (ref: string,) => {




  return `/api/vehicles/${ref}/active`
}

export const vehicleTypesControllerSetActive = async (ref: string,
    setActiveDto: SetActiveDto, options?: Parameters<typeof fetcher>[1]): Promise<VehicleTypeEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<VehicleTypeEntity>(getVehicleTypesControllerSetActiveUrl(ref),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setActiveDto)
  }
);}





export const getVehicleTypesControllerSetActiveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehicleTypesControllerSetActive>>, TError,VehicleTypesControllerSetActiveMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof vehicleTypesControllerSetActive>>, TError,VehicleTypesControllerSetActiveMutationVariables, TContext> => {

const mutationKey = ['vehicleTypesControllerSetActive'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof vehicleTypesControllerSetActive>>, VehicleTypesControllerSetActiveMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  vehicleTypesControllerSetActive(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VehicleTypesControllerSetActiveMutationResult = NonNullable<Awaited<ReturnType<typeof vehicleTypesControllerSetActive>>>
    export type VehicleTypesControllerSetActiveMutationBody = SetActiveDto
    export type VehicleTypesControllerSetActiveMutationError = unknown
    export type VehicleTypesControllerSetActiveMutationVariables = {ref: string;data: SetActiveDto}

    export const useVehicleTypesControllerSetActive = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehicleTypesControllerSetActive>>, TError,VehicleTypesControllerSetActiveMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof vehicleTypesControllerSetActive>>,
        TError,
        VehicleTypesControllerSetActiveMutationVariables,
        TContext
      > => {
      return useMutation(getVehicleTypesControllerSetActiveMutationOptions(options), queryClient);
    }
