/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  RealtimeControllerStream200
} from '../../model';

import { fetcher } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getRealtimeControllerStreamUrl = () => {




  return `/api/events/stream`
}

export const realtimeControllerStream = async ( options?: Parameters<typeof fetcher>[1]): Promise<RealtimeControllerStream200> => {

  return fetcher<RealtimeControllerStream200>(getRealtimeControllerStreamUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getRealtimeControllerStreamQueryKey = () => {
    return [
    `/api/events/stream`
    ] as const;
    }


export const getRealtimeControllerStreamQueryOptions = <TData = Awaited<ReturnType<typeof realtimeControllerStream>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof realtimeControllerStream>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRealtimeControllerStreamQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof realtimeControllerStream>>> = ({ signal }) => realtimeControllerStream({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof realtimeControllerStream>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RealtimeControllerStreamQueryResult = NonNullable<Awaited<ReturnType<typeof realtimeControllerStream>>>
export type RealtimeControllerStreamQueryError = unknown


export function useRealtimeControllerStream<TData = Awaited<ReturnType<typeof realtimeControllerStream>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof realtimeControllerStream>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof realtimeControllerStream>>,
          TError,
          Awaited<ReturnType<typeof realtimeControllerStream>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRealtimeControllerStream<TData = Awaited<ReturnType<typeof realtimeControllerStream>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof realtimeControllerStream>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof realtimeControllerStream>>,
          TError,
          Awaited<ReturnType<typeof realtimeControllerStream>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRealtimeControllerStream<TData = Awaited<ReturnType<typeof realtimeControllerStream>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof realtimeControllerStream>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useRealtimeControllerStream<TData = Awaited<ReturnType<typeof realtimeControllerStream>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof realtimeControllerStream>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRealtimeControllerStreamQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






