/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateUserDto,
  PublicUserEntity,
  SetPasswordDto,
  UpdateUserDto
} from '../../model';

import { fetcher } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getUsersControllerListUrl = () => {




  return `/api/users`
}

export const usersControllerList = async ( options?: Parameters<typeof fetcher>[1]): Promise<PublicUserEntity[]> => {

  return fetcher<PublicUserEntity[]>(getUsersControllerListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getUsersControllerListQueryKey = () => {
    return [
    `/api/users`
    ] as const;
    }


export const getUsersControllerListQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerList>>> = ({ signal }) => usersControllerList({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerList>>>
export type UsersControllerListQueryError = unknown


export function useUsersControllerList<TData = Awaited<ReturnType<typeof usersControllerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerList>>,
          TError,
          Awaited<ReturnType<typeof usersControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerList<TData = Awaited<ReturnType<typeof usersControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerList>>,
          TError,
          Awaited<ReturnType<typeof usersControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersControllerList<TData = Awaited<ReturnType<typeof usersControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersControllerList<TData = Awaited<ReturnType<typeof usersControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUsersControllerCreateUrl = () => {




  return `/api/users`
}

export const usersControllerCreate = async (createUserDto: CreateUserDto, options?: Parameters<typeof fetcher>[1]): Promise<PublicUserEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<PublicUserEntity>(getUsersControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createUserDto)
  }
);}





export const getUsersControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreate>>, TError,UsersControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreate>>, TError,UsersControllerCreateMutationVariables, TContext> => {

const mutationKey = ['usersControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerCreate>>, UsersControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  usersControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerCreate>>>
    export type UsersControllerCreateMutationBody = CreateUserDto
    export type UsersControllerCreateMutationError = unknown
    export type UsersControllerCreateMutationVariables = {data: CreateUserDto}

    export const useUsersControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreate>>, TError,UsersControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerCreate>>,
        TError,
        UsersControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getUsersControllerCreateMutationOptions(options), queryClient);
    }
    export const getUsersControllerUpdateUrl = (id: string,) => {




  return `/api/users/${id}`
}

export const usersControllerUpdate = async (id: string,
    updateUserDto: UpdateUserDto, options?: Parameters<typeof fetcher>[1]): Promise<PublicUserEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<PublicUserEntity>(getUsersControllerUpdateUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateUserDto)
  }
);}





export const getUsersControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdate>>, TError,UsersControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdate>>, TError,UsersControllerUpdateMutationVariables, TContext> => {

const mutationKey = ['usersControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerUpdate>>, UsersControllerUpdateMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  usersControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerUpdate>>>
    export type UsersControllerUpdateMutationBody = UpdateUserDto
    export type UsersControllerUpdateMutationError = unknown
    export type UsersControllerUpdateMutationVariables = {id: string;data: UpdateUserDto}

    export const useUsersControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdate>>, TError,UsersControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerUpdate>>,
        TError,
        UsersControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getUsersControllerUpdateMutationOptions(options), queryClient);
    }
    export const getUsersControllerSetPasswordUrl = (id: string,) => {




  return `/api/users/${id}/password`
}

export const usersControllerSetPassword = async (id: string,
    setPasswordDto: SetPasswordDto, options?: Parameters<typeof fetcher>[1]): Promise<PublicUserEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<PublicUserEntity>(getUsersControllerSetPasswordUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setPasswordDto)
  }
);}





export const getUsersControllerSetPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerSetPassword>>, TError,UsersControllerSetPasswordMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerSetPassword>>, TError,UsersControllerSetPasswordMutationVariables, TContext> => {

const mutationKey = ['usersControllerSetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerSetPassword>>, UsersControllerSetPasswordMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  usersControllerSetPassword(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerSetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerSetPassword>>>
    export type UsersControllerSetPasswordMutationBody = SetPasswordDto
    export type UsersControllerSetPasswordMutationError = unknown
    export type UsersControllerSetPasswordMutationVariables = {id: string;data: SetPasswordDto}

    export const useUsersControllerSetPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerSetPassword>>, TError,UsersControllerSetPasswordMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerSetPassword>>,
        TError,
        UsersControllerSetPasswordMutationVariables,
        TContext
      > => {
      return useMutation(getUsersControllerSetPasswordMutationOptions(options), queryClient);
    }
    export const getUsersControllerDeactivateUrl = (id: string,) => {




  return `/api/users/${id}/deactivate`
}

export const usersControllerDeactivate = async (id: string, options?: Parameters<typeof fetcher>[1]): Promise<PublicUserEntity> => {

  return fetcher<PublicUserEntity>(getUsersControllerDeactivateUrl(id),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getUsersControllerDeactivateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerDeactivate>>, TError,UsersControllerDeactivateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerDeactivate>>, TError,UsersControllerDeactivateMutationVariables, TContext> => {

const mutationKey = ['usersControllerDeactivate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerDeactivate>>, UsersControllerDeactivateMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  usersControllerDeactivate(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerDeactivateMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerDeactivate>>>

    export type UsersControllerDeactivateMutationError = unknown
    export type UsersControllerDeactivateMutationVariables = {id: string}

    export const useUsersControllerDeactivate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerDeactivate>>, TError,UsersControllerDeactivateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerDeactivate>>,
        TError,
        UsersControllerDeactivateMutationVariables,
        TContext
      > => {
      return useMutation(getUsersControllerDeactivateMutationOptions(options), queryClient);
    }
