/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type AuthMeEntityPermissionsItem = typeof AuthMeEntityPermissionsItem[keyof typeof AuthMeEntityPermissionsItem];


export const AuthMeEntityPermissionsItem = {
  'trip:cancel': 'trip:cancel',
  'trip:edit-past': 'trip:edit-past',
  'trip:edit-price': 'trip:edit-price',
  'client:edit': 'client:edit',
  'company:edit': 'company:edit',
  'user:manage': 'user:manage',
  'driver:reactivate': 'driver:reactivate',
  'vehicle:reactivate': 'vehicle:reactivate',
  'client:create-past-event': 'client:create-past-event',
} as const;
