/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { AuthMeEntityRole } from './authMeEntityRole';

export interface AuthMeEntity {
  id: string;
  email: string;
  role: AuthMeEntityRole;
  firstName: string;
  lastName: string;
}
