/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type AuthMeEntityRole = typeof AuthMeEntityRole[keyof typeof AuthMeEntityRole];


export const AuthMeEntityRole = {
  ADMIN: 'ADMIN',
  DISPATCHER: 'DISPATCHER',
} as const;
