/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type CancelAssignmentDtoCancellationFee = typeof CancelAssignmentDtoCancellationFee[keyof typeof CancelAssignmentDtoCancellationFee];


export const CancelAssignmentDtoCancellationFee = {
  FREE: 'FREE',
  FIFTY: 'FIFTY',
  SEVENTYFIVE: 'SEVENTYFIVE',
  HUNDRED: 'HUNDRED',
} as const;
