/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { CancelAssignmentDtoCancellationFee } from './cancelAssignmentDtoCancellationFee';

export interface CancelAssignmentDto {
  cancellationFee?: CancelAssignmentDtoCancellationFee;
}
