/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { ClientEntityBilling } from './clientEntityBilling';
import type { ClientEntityClientType } from './clientEntityClientType';

export interface ClientEntity {
  name: string;
  id: string;
  ref: string;
  clientType: ClientEntityClientType;
  /** @nullable */
  contactFirstName: string | null;
  /** @nullable */
  contactLastName: string | null;
  /** @nullable */
  company: string | null;
  /** @nullable */
  acronym: string | null;
  /** @nullable */
  refPoOther: string | null;
  /** @nullable */
  address: string | null;
  /** @nullable */
  postalCode: string | null;
  /** @nullable */
  city: string | null;
  /** @nullable */
  countryCode: string | null;
  /** @nullable */
  vatNumber: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  billing: ClientEntityBilling;
  /** @nullable */
  pocName: string | null;
  /** @nullable */
  pocPhone: string | null;
  /** @nullable */
  pocEmail: string | null;
  /** @nullable */
  eventCountry: string | null;
  /** @nullable */
  eventArea: string | null;
  /** @nullable */
  eventStartDate: string | null;
  /** @nullable */
  eventEndDate: string | null;
  active: boolean;
  createdAt: string;
  updatedAt: string;
}
