/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { ClientEntity } from './clientEntity';

export interface ClientListEntity {
  data: ClientEntity[];
  total: number;
  page: number;
  limit: number;
}
