/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { ClientsControllerListExcludeType } from './clientsControllerListExcludeType';
import type { ClientsControllerListType } from './clientsControllerListType';

export type ClientsControllerListParams = {
/**
 * Matches against ref, company/contact name, email and acronym (case-insensitive substring).
 */
search?: string;
type?: ClientsControllerListType;
/**
 * The complement of `type` — the Invoicing Customer tab wants every account
 * that is not an Event, since Events have their own selector next to it.
 * Server-side for the same reason as the filters below: dropping the
 * unwanted rows from an already-paginated page would silently shorten the
 * list rather than shrink the query.
 */
excludeType?: ClientsControllerListExcludeType;
/**
 * The three filters below narrow an Events listing down to the accounts a
 * driver or fleet vehicle based at that location may actually be linked to
 * — the legacy's "Link to an Event" popup (openEventLinkModal,
 * common.js:3034). They are Prisma filters rather than a client-side pass
 * over the current page because this endpoint is paginated: filtering the
 * page would hide a mismatched event without shrinking the result set.
 * EventLinkService enforces the same rules on write.
 */
eventCountry?: string;
eventArea?: string;
/**
 * Drops Events whose end date has already passed.
 */
eventNotEnded?: boolean;
includeInactive?: boolean;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
