/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type ClientBaseEntityClientType = typeof ClientBaseEntityClientType[keyof typeof ClientBaseEntityClientType];


export const ClientBaseEntityClientType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
  EVENT: 'EVENT',
} as const;
