/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type ClientEntityClientType = typeof ClientEntityClientType[keyof typeof ClientEntityClientType];


export const ClientEntityClientType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
  EVENT: 'EVENT',
} as const;
