/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { ClientsControllerListType } from './clientsControllerListType';

export type ClientsControllerListParams = {
/**
 * Matches against ref, company/contact name, email and acronym (case-insensitive substring).
 */
search?: string;
type?: ClientsControllerListType;
includeInactive?: boolean;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
