/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type ClientsControllerListExcludeType = typeof ClientsControllerListExcludeType[keyof typeof ClientsControllerListExcludeType];


export const ClientsControllerListExcludeType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
  EVENT: 'EVENT',
} as const;
