/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface CompanyInfoEntity {
  id: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  legalName?: string | null;
  /** @nullable */
  street1?: string | null;
  /** @nullable */
  zipCode?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  countryCode?: string | null;
  /** @nullable */
  vatNbr?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  ownerSurname?: string | null;
  /** @nullable */
  ownerName?: string | null;
  /** @nullable */
  mobile?: string | null;
  /** @nullable */
  ownerEmail?: string | null;
  saved: boolean;
}
