/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type CreateClientDtoClientType = typeof CreateClientDtoClientType[keyof typeof CreateClientDtoClientType];


export const CreateClientDtoClientType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
  EVENT: 'EVENT',
} as const;
