/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface CreateDriverDto {
  countryCode?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  company?: string;
  area?: string;
  email?: string;
  eventsOnly?: boolean;
  eventCountry?: string;
  eventArea?: string;
  /** Ref of the linked event Client account (e.g. "CE1"). */
  eventRef?: string;
}
