/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type CreateClientDtoBilling = typeof CreateClientDtoBilling[keyof typeof CreateClientDtoBilling];


export const CreateClientDtoBilling = {
  ACCOUNT: 'ACCOUNT',
  CASH: 'CASH',
  CARD: 'CARD',
} as const;
