/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { CreateTripDtoBilling } from './createTripDtoBilling';
import type { CreateTripDtoService } from './createTripDtoService';

export interface CreateTripDto {
  countryCode: string;
  area?: string;
  pickupAt: string;
  pickupLocation: string;
  dropoffLocation?: string;
  service: CreateTripDtoService;
  hours?: number;
  instructions?: string;
  clientRef: string;
  /** @minLength 1 */
  passengerName: string;
  pocName?: string;
  pocPhone?: string;
  pocEmail?: string;
  tracking?: boolean;
  paxCount?: number;
  /** VehicleType NAME (not id/ref). */
  vehicleType?: string;
  fleetRegNbr?: string;
  priceEur?: number;
  partnerRateEur?: number;
  driverRef?: string;
  billing?: CreateTripDtoBilling;
  flightNumber?: string;
  bufferTime?: number;
  fboAddress?: string;
  tailNbr?: string;
  /** Name to write on the pickup sign — the attached file is uploaded separately. */
  nameboard?: string;
  pickupIata?: string;
  dropoffIata?: string;
  /**
     * IANA zone the client read the typed date/time in to build `pickupAt`
     * (geocoded from the pickup address). Optional: falls back to the country's
     * default timezone, which is all the legacy ever had.
     */
  pickupTimezone?: string;
  subContractor?: boolean;
  partnerRef?: string;
  /** Manual ref override — 409 if it already exists. */
  ref?: string;
}
