/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type CreateTripDtoService = typeof CreateTripDtoService[keyof typeof CreateTripDtoService];


export const CreateTripDtoService = {
  TSF: 'TSF',
  ASD: 'ASD',
  SPEC: 'SPEC',
} as const;
