/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type CreateTripDtoBilling = typeof CreateTripDtoBilling[keyof typeof CreateTripDtoBilling];


export const CreateTripDtoBilling = {
  ACCOUNT: 'ACCOUNT',
  CASH: 'CASH',
  CARD: 'CARD',
} as const;
