/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { CreateClientDtoBilling } from './createClientDtoBilling';
import type { CreateClientDtoClientType } from './createClientDtoClientType';

export interface CreateClientDto {
  clientType: CreateClientDtoClientType;
  contactFirstName?: string;
  contactLastName?: string;
  company?: string;
  acronym?: string;
  refPoOther?: string;
  address?: string;
  postalCode?: string;
  city?: string;
  countryCode?: string;
  vatNumber?: string;
  email?: string;
  billing?: CreateClientDtoBilling;
  pocName?: string;
  pocPhone?: string;
  pocEmail?: string;
  eventCountry?: string;
  eventArea?: string;
  eventStartDate?: string;
  eventEndDate?: string;
}
