/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface CreateInvoiceDto {
  /** @minItems 1 */
  tripRefs: string[];
  clientRef?: string;
  eventRef?: string;
  periodStart?: string;
  periodEnd?: string;
}
