/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface CreateFleetVehicleDto {
  /** Vehicle-type NAME (not id/ref) — matches an existing VehicleType.name. */
  category: string;
  regNbr: string;
  make: string;
  model: string;
  yearOfBuild: number;
  fourWD: boolean;
  /**
     * @minimum 0
     * @maximum 50
     */
  nbPax: number;
  color?: string;
  /** @maxLength 6 */
  acronym?: string;
  isLocal?: boolean;
  countryCode?: string;
  area?: string;
  partnerCompany?: string;
  /** Driver ref (e.g. "D-FR-INT-001") to reserve this vehicle for — external vehicles only. */
  driverRef?: string;
  eventsOnly?: boolean;
  eventCountry?: string;
  eventArea?: string;
  eventRef?: string;
}
