/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDtoRole } from './createUserDtoRole';

export interface CreateUserDto {
  email: string;
  /** @minLength 8 */
  password: string;
  role: CreateUserDtoRole;
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  phone?: string;
}
