/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type DriversControllerListParams = {
/**
 * Matches against ref, firstName/lastName/company/email/phone (case-insensitive substring).
 */
search?: string;
includeInactive?: boolean;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
