/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { DriverUnavailabilityEntityType } from './driverUnavailabilityEntityType';

export interface DriverUnavailabilityEntity {
  id: string;
  driverId: string;
  type: DriverUnavailabilityEntityType;
  /** @nullable */
  date: string | null;
  /** @nullable */
  startDate: string | null;
  /** @nullable */
  endDate: string | null;
}
