/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type DriverUnavailabilityEntityType = typeof DriverUnavailabilityEntityType[keyof typeof DriverUnavailabilityEntityType];


export const DriverUnavailabilityEntityType = {
  OFF: 'OFF',
  HOLIDAYS: 'HOLIDAYS',
  SICK: 'SICK',
} as const;
