/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface DriverBaseEntity {
  id: string;
  ref: string;
  /** @nullable */
  countryCode: string | null;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  company: string | null;
  /** @nullable */
  email: string | null;
  area: string;
  eventsOnly: boolean;
  /** @nullable */
  eventCountry: string | null;
  /** @nullable */
  eventArea: string | null;
  /** @nullable */
  eventClientId: string | null;
  active: boolean;
  createdAt: string;
  updatedAt: string;
}
