/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { FleetVehicleEntity } from './fleetVehicleEntity';

export interface FleetVehicleListEntity {
  data: FleetVehicleEntity[];
  total: number;
  page: number;
  limit: number;
}
