/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type FleetVehiclesControllerListParams = {
/**
 * Matches against ref, regNbr, make/model/acronym (case-insensitive substring).
 */
search?: string;
includeInactive?: boolean;
/**
 * Drops vehicles marked unavailable today (repair / service / bodywork)
 * and Events-scoped vehicles outside their event's date range — the
 * legacy's isEffectivelyActive, which gated the Reg Nbr picker
 * (populateFleetRegOptions, common.js:935).
 */
availableOnly?: boolean;
/**
 * Trip vehicle-type name the vehicle has to be able to service — resolved
 * through VEHICLE_COMPATIBILITY (e.g. a "Lugg." booking also accepts a
 * "Van"). Same rule the trip create/update already enforces on write; here
 * it stops an incompatible vehicle from being offered in the first place.
 */
compatibleWith?: string;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
