/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type FleetUnavailabilityEntityType = typeof FleetUnavailabilityEntityType[keyof typeof FleetUnavailabilityEntityType];


export const FleetUnavailabilityEntityType = {
  REPAIR: 'REPAIR',
  SERVICE: 'SERVICE',
  BODYWORK: 'BODYWORK',
} as const;
