/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { FleetUnavailabilityEntityType } from './fleetUnavailabilityEntityType';

export interface FleetUnavailabilityEntity {
  id: string;
  fleetVehicleId: string;
  type: FleetUnavailabilityEntityType;
  startDate: string;
  endDate: string;
}
