/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface FlightCheckResponseEntity {
  ok: boolean;
  configured: boolean;
  /** @nullable */
  match: boolean | null;
  message?: string;
  /** @nullable */
  scheduledDeparture?: string | null;
  /** @nullable */
  scheduledArrival?: string | null;
}
