/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface GeocodeTzEntity {
  tz: string;
  lat: number;
  lon: number;
  displayName: string;
  /** @nullable */
  countryCode: string | null;
  isAirport: boolean;
  /** @nullable */
  iata: string | null;
}
