/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { ClientBaseEntity } from './clientBaseEntity';
import type { InvoiceTripEntity } from './invoiceTripEntity';

export interface InvoiceEntity {
  totalHT: string;
  vatRate: string;
  totalTTC: string;
  id: string;
  ref: string;
  clientId: string;
  client: ClientBaseEntity;
  isEvent: boolean;
  /** @nullable */
  refPo: string | null;
  /** @nullable */
  periodStart: string | null;
  /** @nullable */
  periodEnd: string | null;
  createdAt: string;
  trips: InvoiceTripEntity[];
}
