/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface InvoicingPeriodEntity {
  /** Paris-local `yyyy-MM-dd`, inclusive. */
  start: string;
  /** Paris-local `yyyy-MM-dd`, inclusive. */
  end: string;
}
