/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type InvoiceTripRecordEntityBilling = typeof InvoiceTripRecordEntityBilling[keyof typeof InvoiceTripRecordEntityBilling] | null;


export const InvoiceTripRecordEntityBilling = {
  ACCOUNT: 'ACCOUNT',
  CASH: 'CASH',
  CARD: 'CARD',
} as const;
