/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type InvoiceTripRecordEntityService = typeof InvoiceTripRecordEntityService[keyof typeof InvoiceTripRecordEntityService];


export const InvoiceTripRecordEntityService = {
  TSF: 'TSF',
  ASD: 'ASD',
  SPEC: 'SPEC',
} as const;
