/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { TripBaseEntity } from './tripBaseEntity';

export interface InvoiceTripEntity {
  invoiceId: string;
  tripId: string;
  trip: TripBaseEntity;
}
