/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { InvoiceTripRecordEntityBilling } from './invoiceTripRecordEntityBilling';
import type { InvoiceTripRecordEntityCancellationFee } from './invoiceTripRecordEntityCancellationFee';
import type { InvoiceTripRecordEntityService } from './invoiceTripRecordEntityService';
import type { VehicleTypeEntity } from './vehicleTypeEntity';

export interface InvoiceTripRecordEntity {
  /** @nullable */
  priceEur: string | null;
  /** @nullable */
  partnerRateEur: string | null;
  /** @nullable */
  vehicleType: VehicleTypeEntity | null;
  id: string;
  ref: string;
  /** @nullable */
  countryCode: string | null;
  /** @nullable */
  area: string | null;
  /** @nullable */
  timezone: string | null;
  pickupAt: string;
  pickupLocation: string;
  /** @nullable */
  dropoffLocation: string | null;
  service: InvoiceTripRecordEntityService;
  /** @nullable */
  hours: number | null;
  /** @nullable */
  instructions: string | null;
  clientId: string;
  passengerName: string;
  /** @nullable */
  pocName: string | null;
  /** @nullable */
  pocPhone: string | null;
  /** @nullable */
  pocEmail: string | null;
  tracking: boolean;
  /** @nullable */
  paxCount: number | null;
  /** @nullable */
  vehicleTypeId: string | null;
  /** @nullable */
  fleetVehicleId: string | null;
  /** @nullable */
  driverId: string | null;
  /** @nullable */
  billing: InvoiceTripRecordEntityBilling;
  /** @nullable */
  flightNumber: string | null;
  /** @nullable */
  bufferTime: number | null;
  /** @nullable */
  fboAddress: string | null;
  /** @nullable */
  tailNbr: string | null;
  /** @nullable */
  nameboard: string | null;
  /** @nullable */
  nameboardUrl: string | null;
  /** @nullable */
  pickupIata: string | null;
  /** @nullable */
  dropoffIata: string | null;
  subContractor: boolean;
  /** @nullable */
  partnerId: string | null;
  dispatched: boolean;
  invoiced: boolean;
  assignmentCancelled: boolean;
  /** @nullable */
  assignmentCancelledAt: string | null;
  /** @nullable */
  cancellationFee: InvoiceTripRecordEntityCancellationFee;
  createdAt: string;
  updatedAt: string;
}
