/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { BillingOptionEntity } from './billingOptionEntity';
import type { CountryEntity } from './countryEntity';
import type { FleetColorEntity } from './fleetColorEntity';
import type { MajorCityEntity } from './majorCityEntity';
import type { MetaEntityCategoryModels } from './metaEntityCategoryModels';
import type { MetaEntityFleetModelsByMake } from './metaEntityFleetModelsByMake';
import type { MetaEntityVehicleCompatibility } from './metaEntityVehicleCompatibility';
import type { VehicleTypeEntity } from './vehicleTypeEntity';

export interface MetaEntity {
  /** Available models keyed by make. */
  fleetModelsByMake: MetaEntityFleetModelsByMake;
  /** Compatible fleet categories keyed by vehicle-type name. */
  vehicleCompatibility: MetaEntityVehicleCompatibility;
  /** Allowed models keyed by [category][make]. */
  categoryModels: MetaEntityCategoryModels;
  countries: CountryEntity[];
  vehicleTypes: VehicleTypeEntity[];
  billingOptions: BillingOptionEntity[];
  fleetMakes: string[];
  fleetMinYear: number;
  fleetMaxYear: number;
  majorCities: MajorCityEntity[];
  fleetColors: FleetColorEntity[];
  fleetDefaultColor: string;
}
