/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

/**
 * Available models keyed by make.
 */
export type MetaEntityFleetModelsByMake = {[key: string]: string[]};
