/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

/**
 * Allowed models keyed by [category][make].
 */
export type MetaEntityCategoryModels = {[key: string]: {[key: string]: string[]}};
