/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type MetaControllerGetAreaSuggestionsParams = {
/**
 * The country already chosen in the paired Country field — a plain code
 * ("FR", "MC") or a US regional one ("US-NY"). Optional: with no country
 * chosen there is nothing to suggest and "Local" is not allowed either,
 * so the frontend can call this unconditionally.
 */
countryCode?: string;
};
