/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type NotifyStepDtoStep = typeof NotifyStepDtoStep[keyof typeof NotifyStepDtoStep];


export const NotifyStepDtoStep = {
  ACCEPTED: 'ACCEPTED',
  ENROUTE: 'ENROUTE',
  ARRIVED: 'ARRIVED',
  ONBOARD: 'ONBOARD',
  DROPPED: 'DROPPED',
} as const;
