/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { PublicUserEntityRole } from './publicUserEntityRole';

export interface PublicUserEntity {
  id: string;
  email: string;
  role: PublicUserEntityRole;
  firstName: string;
  lastName: string;
  /** @nullable */
  phone: string | null;
  active: boolean;
  /** @nullable */
  deactivatedAt: string | null;
  /** @nullable */
  lastLoginAt: string | null;
  createdAt: string;
}
