/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { TripStepEntity } from './tripStepEntity';

export interface PublicTripEntity {
  ref: string;
  tracking: boolean;
  assignmentCancelled: boolean;
  clientName: string;
  clientRef: string;
  /** @nullable */
  driverName: string | null;
  passengerName: string;
  /** @nullable */
  paxCount: number | null;
  /** @nullable */
  pocName: string | null;
  /** @nullable */
  pocPhone: string | null;
  pickupAt: string;
  /** @nullable */
  timezone: string | null;
  pickupLocation: string;
  /** @nullable */
  dropoffLocation: string | null;
  /** @nullable */
  vehicleTypeName: string | null;
  /** @nullable */
  instructions: string | null;
  steps: TripStepEntity[];
}
