/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { PublicTripEntity } from './publicTripEntity';

export interface PublicTripActionResponseEntity {
  ok: boolean;
  trip: PublicTripEntity;
  skipped?: boolean;
}
