/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { ReactivationCandidateEntity } from './reactivationCandidateEntity';

export interface ReactivationCandidatesEntity {
  drivers: ReactivationCandidateEntity[];
  fleetVehicles: ReactivationCandidateEntity[];
}
