/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface ReactivationCandidateEntity {
  ref: string;
  /** Row label: the driver's name, or "REG-NBR (Category)" for a vehicle. */
  label: string;
  /** The Event it is still scoped to — the one it is dormant under. */
  previousEventRef: string;
  previousEventName: string;
}
