/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface ReactivateResponseEntity {
  ok: boolean;
  /** How many drivers were relinked. */
  drivers: number;
  /** How many fleet vehicles were relinked. */
  fleetVehicles: number;
}
