/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { SetDriverUnavailabilityDtoType } from './setDriverUnavailabilityDtoType';

export interface SetDriverUnavailabilityDto {
  /** @nullable */
  type?: SetDriverUnavailabilityDtoType;
  date?: string;
  startDate?: string;
  endDate?: string;
}
