/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type SetDriverUnavailabilityDtoType = typeof SetDriverUnavailabilityDtoType[keyof typeof SetDriverUnavailabilityDtoType] | null;


export const SetDriverUnavailabilityDtoType = {
  OFF: 'OFF',
  HOLIDAYS: 'HOLIDAYS',
  SICK: 'SICK',
} as const;
