/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type SetFleetUnavailabilityDtoType = typeof SetFleetUnavailabilityDtoType[keyof typeof SetFleetUnavailabilityDtoType] | null;


export const SetFleetUnavailabilityDtoType = {
  REPAIR: 'REPAIR',
  SERVICE: 'SERVICE',
  BODYWORK: 'BODYWORK',
} as const;
