/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface SubcontractEmailEntity {
  /**
     * The partner's email on file, or null when there is none and no draft can be written.
     * @nullable
     */
  to: string | null;
  subject: string;
  body: string;
}
