/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type TripStepEntityStep = typeof TripStepEntityStep[keyof typeof TripStepEntityStep];


export const TripStepEntityStep = {
  TRANSMITTED: 'TRANSMITTED',
  RECEIVED: 'RECEIVED',
  ACCEPTED: 'ACCEPTED',
  ENROUTE: 'ENROUTE',
  ARRIVED: 'ARRIVED',
  ONBOARD: 'ONBOARD',
  DROPPED: 'DROPPED',
} as const;
