/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { TripsControllerListCategory } from './tripsControllerListCategory';
import type { TripsControllerListPeriod } from './tripsControllerListPeriod';

export type TripsControllerListParams = {
/**
 * Defaults to 'upcoming' in TripsService.list() — see periodDateRange().
 */
period?: TripsControllerListPeriod;
/**
 * Defaults to 'daily' in TripsService.list().
 */
category?: TripsControllerListCategory;
};
