/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type TripsControllerListCategory = typeof TripsControllerListCategory[keyof typeof TripsControllerListCategory];


export const TripsControllerListCategory = {
  daily: 'daily',
  event: 'event',
  all: 'all',
} as const;
