/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { VehicleTypeEntity } from './vehicleTypeEntity';

export interface TripFleetVehicleEntity {
  id: string;
  ref: string;
  categoryId: string;
  category: VehicleTypeEntity;
  regNbr: string;
  make: string;
  model: string;
  yearOfBuild: number;
  fourWD: boolean;
  nbPax: number;
  color: string;
  /** @nullable */
  acronym: string | null;
  isLocal: boolean;
  /** @nullable */
  countryCode: string | null;
  /** @nullable */
  area: string | null;
  /** @nullable */
  partnerCompany: string | null;
  /** @nullable */
  driverId: string | null;
  eventsOnly: boolean;
  /** @nullable */
  eventCountry: string | null;
  /** @nullable */
  eventArea: string | null;
  /** @nullable */
  eventClientId: string | null;
  active: boolean;
  createdAt: string;
  updatedAt: string;
}
