/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { TripStepEntityStep } from './tripStepEntityStep';

export interface TripStepEntity {
  id: string;
  tripId: string;
  step: TripStepEntityStep;
  occurredAt: string;
}
