/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { TripsControllerSubcontractEmailKind } from './tripsControllerSubcontractEmailKind';

export type TripsControllerSubcontractEmailParams = {
kind: TripsControllerSubcontractEmailKind;
/**
 * Whose draft to write, when it isn't (or is no longer) the trip's own
 * partner. The cancellation notice needs this: the front reads the draft
 * *before* clearing partnerRef, and the legacy had the same ordering
 * constraint ("`partner` must be captured by the caller BEFORE the trip's
 * partnerRef is cleared", common.js:2686).
 */
partnerRef?: string;
};
