/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type TripBaseEntityCancellationFee = typeof TripBaseEntityCancellationFee[keyof typeof TripBaseEntityCancellationFee] | null;


export const TripBaseEntityCancellationFee = {
  FREE: 'FREE',
  FIFTY: 'FIFTY',
  SEVENTYFIVE: 'SEVENTYFIVE',
  HUNDRED: 'HUNDRED',
} as const;
