/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type TripsControllerListService = typeof TripsControllerListService[keyof typeof TripsControllerListService];


export const TripsControllerListService = {
  TSF: 'TSF',
  ASD: 'ASD',
  SPEC: 'SPEC',
} as const;
