/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type TripEntityCancellationFee = typeof TripEntityCancellationFee[keyof typeof TripEntityCancellationFee] | null;


export const TripEntityCancellationFee = {
  FREE: 'FREE',
  FIFTY: 'FIFTY',
  SEVENTYFIVE: 'SEVENTYFIVE',
  HUNDRED: 'HUNDRED',
} as const;
