/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { TripsControllerListCategory } from './tripsControllerListCategory';
import type { TripsControllerListPeriod } from './tripsControllerListPeriod';
import type { TripsControllerListService } from './tripsControllerListService';

export type TripsControllerListParams = {
/**
 * Explicit pickup window, as ISO instants: `from` inclusive, `to` exclusive.
 *
 * For the callers whose window is a real date range rather than one of the
 * named periods below — the Planning Gantt navigates to an arbitrary date
 * plus a 1-3 day span, the Invoicing/Partner logs to a billing month. They
 * used to ask for `period=all` (no bound at all) and narrow in the browser.
 *
 * Giving either bound replaces `period` entirely, so a caller that means
 * "this window" cannot accidentally also get the 'upcoming' default.
 */
from?: string;
to?: string;
/**
 * Only bookings farmed out to a partner — the Invoicing Partner log, which
 * shows nothing else. Omit for no filtering; `false` is not a filter for
 * "no partner", there is no caller for that.
 */
hasPartner?: boolean;
/**
 * The Bookings board's search box: ref, account, passenger or driver.
 *
 * Token by token (every word must appear somewhere, in any field), the same
 * rule the Clients/Drivers/Vehicles searches use — see searchTokensFilter for
 * why. `name` is derived, never stored, so the fields it is derived from are
 * what gets searched: the account's company and contact names, the driver's
 * and the partner's.
 */
search?: string;
/**
 * Exact account, by ref.
 */
clientRef?: string;
/**
 * Exact driver, by ref. Deliberately the driver only: a booking farmed out
 * to a partner does not match, which is what the board has always done even
 * though its Driver column falls back to showing the partner.
 */
driverRef?: string;
/**
 * Substring of the passenger's name, case-insensitive.
 */
passenger?: string;
/**
 * Exact vehicle type, by name.
 */
vehicleType?: string;
service?: TripsControllerListService;
/**
 * Defaults to 'upcoming' in TripsService.list() — see periodDateRange().
 */
period?: TripsControllerListPeriod;
/**
 * Defaults to 'daily' in TripsService.list().
 */
category?: TripsControllerListCategory;
/**
 * Opt-in "live dispatch board" window: drops a trip whose pickup was before
 * today (Paris) once it already has a driver — an already-handled job is
 * clutter on the board, while an unassigned one still needs attention.
 *
 * Off by default on purpose. In the legacy this was `baseVisibility`
 * (dispatcher.html:349-363), applied client-side by the Bookings page and
 * by nothing else: Invoicing, Events, the Partner log and the Planning
 * Gantt all read the unfiltered list, and must keep seeing past assigned
 * trips (Invoicing's whole job is billing completed months).
 */
board?: boolean;
};
