/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type TripsControllerListPeriod = typeof TripsControllerListPeriod[keyof typeof TripsControllerListPeriod];


export const TripsControllerListPeriod = {
  upcoming: 'upcoming',
  today: 'today',
  week: 'week',
  past: 'past',
  all: 'all',
} as const;
