/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type TripEntityService = typeof TripEntityService[keyof typeof TripEntityService];


export const TripEntityService = {
  TSF: 'TSF',
  ASD: 'ASD',
  SPEC: 'SPEC',
} as const;
