/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { ClientBaseEntity } from './clientBaseEntity';
import type { DriverBaseEntity } from './driverBaseEntity';
import type { TripEntityBilling } from './tripEntityBilling';
import type { TripEntityCancellationFee } from './tripEntityCancellationFee';
import type { TripEntityService } from './tripEntityService';
import type { TripFleetVehicleEntity } from './tripFleetVehicleEntity';
import type { TripStepEntity } from './tripStepEntity';
import type { VehicleTypeEntity } from './vehicleTypeEntity';

export interface TripEntity {
  /** @nullable */
  priceEur: string | null;
  /** @nullable */
  partnerRateEur: string | null;
  client: ClientBaseEntity;
  /** @nullable */
  driver: DriverBaseEntity | null;
  /** @nullable */
  partner: DriverBaseEntity | null;
  /** @nullable */
  vehicleType: VehicleTypeEntity | null;
  /** @nullable */
  fleetVehicle: TripFleetVehicleEntity | null;
  steps: TripStepEntity[];
  id: string;
  ref: string;
  /** @nullable */
  countryCode: string | null;
  /** @nullable */
  area: string | null;
  /** @nullable */
  timezone: string | null;
  pickupAt: string;
  pickupLocation: string;
  /** @nullable */
  dropoffLocation: string | null;
  service: TripEntityService;
  /** @nullable */
  hours: number | null;
  /** @nullable */
  instructions: string | null;
  clientId: string;
  passengerName: string;
  /** @nullable */
  pocName: string | null;
  /** @nullable */
  pocPhone: string | null;
  /** @nullable */
  pocEmail: string | null;
  tracking: boolean;
  /** @nullable */
  paxCount: number | null;
  /** @nullable */
  vehicleTypeId: string | null;
  /** @nullable */
  fleetVehicleId: string | null;
  /** @nullable */
  driverId: string | null;
  /** @nullable */
  billing: TripEntityBilling;
  /** @nullable */
  flightNumber: string | null;
  /** @nullable */
  bufferTime: number | null;
  /** @nullable */
  fboAddress: string | null;
  /** @nullable */
  tailNbr: string | null;
  /** @nullable */
  nameboard: string | null;
  /** @nullable */
  nameboardUrl: string | null;
  /** @nullable */
  pickupIata: string | null;
  /** @nullable */
  dropoffIata: string | null;
  subContractor: boolean;
  /** @nullable */
  partnerId: string | null;
  dispatched: boolean;
  invoiced: boolean;
  assignmentCancelled: boolean;
  /** @nullable */
  assignmentCancelledAt: string | null;
  /** @nullable */
  cancellationFee: TripEntityCancellationFee;
  createdAt: string;
  updatedAt: string;
}
