/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface UpdateCompanyInfoDto {
  name: string;
  legalName: string;
  street1: string;
  zipCode: string;
  city: string;
  countryCode: string;
  vatNbr: string;
  email: string;
  website: string;
  ownerSurname: string;
  ownerName: string;
  mobile: string;
  ownerEmail: string;
}
