/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type UpdateClientDtoClientType = typeof UpdateClientDtoClientType[keyof typeof UpdateClientDtoClientType];


export const UpdateClientDtoClientType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
  EVENT: 'EVENT',
} as const;
