/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { UpdateClientDtoBilling } from './updateClientDtoBilling';
import type { UpdateClientDtoClientType } from './updateClientDtoClientType';

export interface UpdateClientDto {
  clientType?: UpdateClientDtoClientType;
  contactFirstName?: string;
  contactLastName?: string;
  company?: string;
  /**
     * The account's short form, shown in the "Cust / Pax" column of Bookings,
     * Planning and Events. Capped at four the way the legacy capped it — beyond
     * that it stops fitting the column it exists for (clients.html:500-510,
     * which highlighted the field and disabled Create).
     * @maxLength 4
     */
  acronym?: string;
  refPoOther?: string;
  address?: string;
  postalCode?: string;
  city?: string;
  countryCode?: string;
  vatNumber?: string;
  email?: string;
  billing?: UpdateClientDtoBilling;
  pocName?: string;
  pocPhone?: string;
  pocEmail?: string;
  eventCountry?: string;
  eventArea?: string;
  eventStartDate?: string;
  eventEndDate?: string;
}
