/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type UpdateTripDtoBilling = typeof UpdateTripDtoBilling[keyof typeof UpdateTripDtoBilling];


export const UpdateTripDtoBilling = {
  ACCOUNT: 'ACCOUNT',
  CASH: 'CASH',
  CARD: 'CARD',
} as const;
