/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserDtoRole } from './updateUserDtoRole';

export interface UpdateUserDto {
  email: string;
  role: UpdateUserDtoRole;
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  phone?: string;
}
