/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface UpdateVehicleTypeDto {
  /** @minLength 1 */
  name?: string;
  /** @minimum 1 */
  maxPax?: number;
}
