/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserDtoRole } from './updateUserDtoRole';

export interface UpdateUserDto {
  email: string;
  role: UpdateUserDtoRole;
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  /**
     * Required, as the legacy required it of every access account on create and
     * on edit alike (server.js:262-264, 275-277) — it is how a dispatcher is
     * reached off-hours, not decoration.
     */
  phone: string;
}
