/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type UpdateTripDtoService = typeof UpdateTripDtoService[keyof typeof UpdateTripDtoService];


export const UpdateTripDtoService = {
  TSF: 'TSF',
  ASD: 'ASD',
  SPEC: 'SPEC',
} as const;
