/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface UpdateTripDto {
  /** "Confirm and send" checkbox — best-effort WhatsApp to the POC after saving. */
  notifyDriver?: boolean;
}
