/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export type UpdateUserDtoRole = typeof UpdateUserDtoRole[keyof typeof UpdateUserDtoRole];


export const UpdateUserDtoRole = {
  ADMIN: 'ADMIN',
  DISPATCHER: 'DISPATCHER',
} as const;
