/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface VehicleTypeEntity {
  id: string;
  ref: string;
  name: string;
  maxPax: number;
  active: boolean;
  createdAt: string;
}
