/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */

export interface VerifyDto {
  email: string;
  /** @pattern ^\d{6}$ */
  code: string;
}
