/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateInvoiceDto,
  InvoiceEntity
} from '../../model';

import { fetcher } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getInvoicesControllerListUrl = () => {




  return `/api/invoices`
}

export const invoicesControllerList = async ( options?: Parameters<typeof fetcher>[1]): Promise<InvoiceEntity[]> => {

  return fetcher<InvoiceEntity[]>(getInvoicesControllerListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getInvoicesControllerListQueryKey = () => {
    return [
    `/api/invoices`
    ] as const;
    }


export const getInvoicesControllerListQueryOptions = <TData = Awaited<ReturnType<typeof invoicesControllerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoicesControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInvoicesControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof invoicesControllerList>>> = ({ signal }) => invoicesControllerList({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof invoicesControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InvoicesControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof invoicesControllerList>>>
export type InvoicesControllerListQueryError = unknown


export function useInvoicesControllerList<TData = Awaited<ReturnType<typeof invoicesControllerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoicesControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoicesControllerList>>,
          TError,
          Awaited<ReturnType<typeof invoicesControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoicesControllerList<TData = Awaited<ReturnType<typeof invoicesControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoicesControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoicesControllerList>>,
          TError,
          Awaited<ReturnType<typeof invoicesControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvoicesControllerList<TData = Awaited<ReturnType<typeof invoicesControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoicesControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInvoicesControllerList<TData = Awaited<ReturnType<typeof invoicesControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invoicesControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInvoicesControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getInvoicesControllerCreateUrl = () => {




  return `/api/invoices`
}

export const invoicesControllerCreate = async (createInvoiceDto: CreateInvoiceDto, options?: Parameters<typeof fetcher>[1]): Promise<InvoiceEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<InvoiceEntity>(getInvoicesControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createInvoiceDto)
  }
);}





export const getInvoicesControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invoicesControllerCreate>>, TError,InvoicesControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof invoicesControllerCreate>>, TError,InvoicesControllerCreateMutationVariables, TContext> => {

const mutationKey = ['invoicesControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof invoicesControllerCreate>>, InvoicesControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  invoicesControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InvoicesControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof invoicesControllerCreate>>>
    export type InvoicesControllerCreateMutationBody = CreateInvoiceDto
    export type InvoicesControllerCreateMutationError = unknown
    export type InvoicesControllerCreateMutationVariables = {data: CreateInvoiceDto}

    export const useInvoicesControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invoicesControllerCreate>>, TError,InvoicesControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof invoicesControllerCreate>>,
        TError,
        InvoicesControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getInvoicesControllerCreateMutationOptions(options), queryClient);
    }
