/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FboLookupEntity,
  FlightCheckDto,
  FlightCheckResponseEntity,
  FxRateEntity,
  GeoControllerFboLookupParams,
  GeoControllerFxRateParams,
  GeoControllerGeocodeSearchParams,
  GeoControllerGeocodeTzParams,
  GeoControllerPocSearchParams,
  GeocodeSearchResponseEntity,
  GeocodeTzEntity,
  PocSearchResponseEntity
} from '../../model';

import { fetcher } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGeoControllerGeocodeTzUrl = (params?: GeoControllerGeocodeTzParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/geocode-tz?${stringifiedParams}` : `/api/geocode-tz`
}

export const geoControllerGeocodeTz = async (params?: GeoControllerGeocodeTzParams, options?: Parameters<typeof fetcher>[1]): Promise<GeocodeTzEntity> => {

  return fetcher<GeocodeTzEntity>(getGeoControllerGeocodeTzUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGeoControllerGeocodeTzQueryKey = (params?: GeoControllerGeocodeTzParams,) => {
    return [
    `/api/geocode-tz`, ...(params ? [params] : [])
    ] as const;
    }


export const getGeoControllerGeocodeTzQueryOptions = <TData = Awaited<ReturnType<typeof geoControllerGeocodeTz>>, TError = unknown>(params?: GeoControllerGeocodeTzParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerGeocodeTz>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGeoControllerGeocodeTzQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof geoControllerGeocodeTz>>> = ({ signal }) => geoControllerGeocodeTz(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof geoControllerGeocodeTz>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GeoControllerGeocodeTzQueryResult = NonNullable<Awaited<ReturnType<typeof geoControllerGeocodeTz>>>
export type GeoControllerGeocodeTzQueryError = unknown


export function useGeoControllerGeocodeTz<TData = Awaited<ReturnType<typeof geoControllerGeocodeTz>>, TError = unknown>(
 params: undefined |  GeoControllerGeocodeTzParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerGeocodeTz>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof geoControllerGeocodeTz>>,
          TError,
          Awaited<ReturnType<typeof geoControllerGeocodeTz>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGeoControllerGeocodeTz<TData = Awaited<ReturnType<typeof geoControllerGeocodeTz>>, TError = unknown>(
 params?: GeoControllerGeocodeTzParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerGeocodeTz>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof geoControllerGeocodeTz>>,
          TError,
          Awaited<ReturnType<typeof geoControllerGeocodeTz>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGeoControllerGeocodeTz<TData = Awaited<ReturnType<typeof geoControllerGeocodeTz>>, TError = unknown>(
 params?: GeoControllerGeocodeTzParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerGeocodeTz>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGeoControllerGeocodeTz<TData = Awaited<ReturnType<typeof geoControllerGeocodeTz>>, TError = unknown>(
 params?: GeoControllerGeocodeTzParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerGeocodeTz>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGeoControllerGeocodeTzQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGeoControllerGeocodeSearchUrl = (params?: GeoControllerGeocodeSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/geocode-search?${stringifiedParams}` : `/api/geocode-search`
}

export const geoControllerGeocodeSearch = async (params?: GeoControllerGeocodeSearchParams, options?: Parameters<typeof fetcher>[1]): Promise<GeocodeSearchResponseEntity> => {

  return fetcher<GeocodeSearchResponseEntity>(getGeoControllerGeocodeSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGeoControllerGeocodeSearchQueryKey = (params?: GeoControllerGeocodeSearchParams,) => {
    return [
    `/api/geocode-search`, ...(params ? [params] : [])
    ] as const;
    }


export const getGeoControllerGeocodeSearchQueryOptions = <TData = Awaited<ReturnType<typeof geoControllerGeocodeSearch>>, TError = unknown>(params?: GeoControllerGeocodeSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerGeocodeSearch>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGeoControllerGeocodeSearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof geoControllerGeocodeSearch>>> = ({ signal }) => geoControllerGeocodeSearch(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof geoControllerGeocodeSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GeoControllerGeocodeSearchQueryResult = NonNullable<Awaited<ReturnType<typeof geoControllerGeocodeSearch>>>
export type GeoControllerGeocodeSearchQueryError = unknown


export function useGeoControllerGeocodeSearch<TData = Awaited<ReturnType<typeof geoControllerGeocodeSearch>>, TError = unknown>(
 params: undefined |  GeoControllerGeocodeSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerGeocodeSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof geoControllerGeocodeSearch>>,
          TError,
          Awaited<ReturnType<typeof geoControllerGeocodeSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGeoControllerGeocodeSearch<TData = Awaited<ReturnType<typeof geoControllerGeocodeSearch>>, TError = unknown>(
 params?: GeoControllerGeocodeSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerGeocodeSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof geoControllerGeocodeSearch>>,
          TError,
          Awaited<ReturnType<typeof geoControllerGeocodeSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGeoControllerGeocodeSearch<TData = Awaited<ReturnType<typeof geoControllerGeocodeSearch>>, TError = unknown>(
 params?: GeoControllerGeocodeSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerGeocodeSearch>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGeoControllerGeocodeSearch<TData = Awaited<ReturnType<typeof geoControllerGeocodeSearch>>, TError = unknown>(
 params?: GeoControllerGeocodeSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerGeocodeSearch>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGeoControllerGeocodeSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGeoControllerFboLookupUrl = (params?: GeoControllerFboLookupParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/fbo-lookup?${stringifiedParams}` : `/api/fbo-lookup`
}

export const geoControllerFboLookup = async (params?: GeoControllerFboLookupParams, options?: Parameters<typeof fetcher>[1]): Promise<FboLookupEntity> => {

  return fetcher<FboLookupEntity>(getGeoControllerFboLookupUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGeoControllerFboLookupQueryKey = (params?: GeoControllerFboLookupParams,) => {
    return [
    `/api/fbo-lookup`, ...(params ? [params] : [])
    ] as const;
    }


export const getGeoControllerFboLookupQueryOptions = <TData = Awaited<ReturnType<typeof geoControllerFboLookup>>, TError = unknown>(params?: GeoControllerFboLookupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerFboLookup>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGeoControllerFboLookupQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof geoControllerFboLookup>>> = ({ signal }) => geoControllerFboLookup(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof geoControllerFboLookup>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GeoControllerFboLookupQueryResult = NonNullable<Awaited<ReturnType<typeof geoControllerFboLookup>>>
export type GeoControllerFboLookupQueryError = unknown


export function useGeoControllerFboLookup<TData = Awaited<ReturnType<typeof geoControllerFboLookup>>, TError = unknown>(
 params: undefined |  GeoControllerFboLookupParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerFboLookup>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof geoControllerFboLookup>>,
          TError,
          Awaited<ReturnType<typeof geoControllerFboLookup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGeoControllerFboLookup<TData = Awaited<ReturnType<typeof geoControllerFboLookup>>, TError = unknown>(
 params?: GeoControllerFboLookupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerFboLookup>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof geoControllerFboLookup>>,
          TError,
          Awaited<ReturnType<typeof geoControllerFboLookup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGeoControllerFboLookup<TData = Awaited<ReturnType<typeof geoControllerFboLookup>>, TError = unknown>(
 params?: GeoControllerFboLookupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerFboLookup>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGeoControllerFboLookup<TData = Awaited<ReturnType<typeof geoControllerFboLookup>>, TError = unknown>(
 params?: GeoControllerFboLookupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerFboLookup>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGeoControllerFboLookupQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGeoControllerFlightCheckUrl = () => {




  return `/api/flight-check`
}

export const geoControllerFlightCheck = async (flightCheckDto: FlightCheckDto, options?: Parameters<typeof fetcher>[1]): Promise<FlightCheckResponseEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<FlightCheckResponseEntity>(getGeoControllerFlightCheckUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(flightCheckDto)
  }
);}





export const getGeoControllerFlightCheckMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof geoControllerFlightCheck>>, TError,GeoControllerFlightCheckMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof geoControllerFlightCheck>>, TError,GeoControllerFlightCheckMutationVariables, TContext> => {

const mutationKey = ['geoControllerFlightCheck'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof geoControllerFlightCheck>>, GeoControllerFlightCheckMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  geoControllerFlightCheck(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GeoControllerFlightCheckMutationResult = NonNullable<Awaited<ReturnType<typeof geoControllerFlightCheck>>>
    export type GeoControllerFlightCheckMutationBody = FlightCheckDto
    export type GeoControllerFlightCheckMutationError = unknown
    export type GeoControllerFlightCheckMutationVariables = {data: FlightCheckDto}

    export const useGeoControllerFlightCheck = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof geoControllerFlightCheck>>, TError,GeoControllerFlightCheckMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof geoControllerFlightCheck>>,
        TError,
        GeoControllerFlightCheckMutationVariables,
        TContext
      > => {
      return useMutation(getGeoControllerFlightCheckMutationOptions(options), queryClient);
    }
    export const getGeoControllerPocSearchUrl = (params?: GeoControllerPocSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/poc-search?${stringifiedParams}` : `/api/poc-search`
}

export const geoControllerPocSearch = async (params?: GeoControllerPocSearchParams, options?: Parameters<typeof fetcher>[1]): Promise<PocSearchResponseEntity> => {

  return fetcher<PocSearchResponseEntity>(getGeoControllerPocSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGeoControllerPocSearchQueryKey = (params?: GeoControllerPocSearchParams,) => {
    return [
    `/api/poc-search`, ...(params ? [params] : [])
    ] as const;
    }


export const getGeoControllerPocSearchQueryOptions = <TData = Awaited<ReturnType<typeof geoControllerPocSearch>>, TError = unknown>(params?: GeoControllerPocSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerPocSearch>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGeoControllerPocSearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof geoControllerPocSearch>>> = ({ signal }) => geoControllerPocSearch(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof geoControllerPocSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GeoControllerPocSearchQueryResult = NonNullable<Awaited<ReturnType<typeof geoControllerPocSearch>>>
export type GeoControllerPocSearchQueryError = unknown


export function useGeoControllerPocSearch<TData = Awaited<ReturnType<typeof geoControllerPocSearch>>, TError = unknown>(
 params: undefined |  GeoControllerPocSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerPocSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof geoControllerPocSearch>>,
          TError,
          Awaited<ReturnType<typeof geoControllerPocSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGeoControllerPocSearch<TData = Awaited<ReturnType<typeof geoControllerPocSearch>>, TError = unknown>(
 params?: GeoControllerPocSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerPocSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof geoControllerPocSearch>>,
          TError,
          Awaited<ReturnType<typeof geoControllerPocSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGeoControllerPocSearch<TData = Awaited<ReturnType<typeof geoControllerPocSearch>>, TError = unknown>(
 params?: GeoControllerPocSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerPocSearch>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGeoControllerPocSearch<TData = Awaited<ReturnType<typeof geoControllerPocSearch>>, TError = unknown>(
 params?: GeoControllerPocSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerPocSearch>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGeoControllerPocSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGeoControllerFxRateUrl = (params?: GeoControllerFxRateParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/fx-rate?${stringifiedParams}` : `/api/fx-rate`
}

export const geoControllerFxRate = async (params?: GeoControllerFxRateParams, options?: Parameters<typeof fetcher>[1]): Promise<FxRateEntity> => {

  return fetcher<FxRateEntity>(getGeoControllerFxRateUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGeoControllerFxRateQueryKey = (params?: GeoControllerFxRateParams,) => {
    return [
    `/api/fx-rate`, ...(params ? [params] : [])
    ] as const;
    }


export const getGeoControllerFxRateQueryOptions = <TData = Awaited<ReturnType<typeof geoControllerFxRate>>, TError = unknown>(params?: GeoControllerFxRateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerFxRate>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGeoControllerFxRateQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof geoControllerFxRate>>> = ({ signal }) => geoControllerFxRate(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof geoControllerFxRate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GeoControllerFxRateQueryResult = NonNullable<Awaited<ReturnType<typeof geoControllerFxRate>>>
export type GeoControllerFxRateQueryError = unknown


export function useGeoControllerFxRate<TData = Awaited<ReturnType<typeof geoControllerFxRate>>, TError = unknown>(
 params: undefined |  GeoControllerFxRateParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerFxRate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof geoControllerFxRate>>,
          TError,
          Awaited<ReturnType<typeof geoControllerFxRate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGeoControllerFxRate<TData = Awaited<ReturnType<typeof geoControllerFxRate>>, TError = unknown>(
 params?: GeoControllerFxRateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerFxRate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof geoControllerFxRate>>,
          TError,
          Awaited<ReturnType<typeof geoControllerFxRate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGeoControllerFxRate<TData = Awaited<ReturnType<typeof geoControllerFxRate>>, TError = unknown>(
 params?: GeoControllerFxRateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerFxRate>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGeoControllerFxRate<TData = Awaited<ReturnType<typeof geoControllerFxRate>>, TError = unknown>(
 params?: GeoControllerFxRateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof geoControllerFxRate>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGeoControllerFxRateQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






