/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateFleetVehicleDto,
  FleetVehicleEntity,
  OkResponseEntity,
  SetActiveDto,
  SetFleetDriverDto,
  SetFleetUnavailabilityDto
} from '../../model';

import { fetcher } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getFleetVehiclesControllerListUrl = () => {




  return `/api/fleet-vehicles`
}

export const fleetVehiclesControllerList = async ( options?: Parameters<typeof fetcher>[1]): Promise<FleetVehicleEntity[]> => {

  return fetcher<FleetVehicleEntity[]>(getFleetVehiclesControllerListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFleetVehiclesControllerListQueryKey = () => {
    return [
    `/api/fleet-vehicles`
    ] as const;
    }


export const getFleetVehiclesControllerListQueryOptions = <TData = Awaited<ReturnType<typeof fleetVehiclesControllerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fleetVehiclesControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFleetVehiclesControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof fleetVehiclesControllerList>>> = ({ signal }) => fleetVehiclesControllerList({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fleetVehiclesControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FleetVehiclesControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof fleetVehiclesControllerList>>>
export type FleetVehiclesControllerListQueryError = unknown


export function useFleetVehiclesControllerList<TData = Awaited<ReturnType<typeof fleetVehiclesControllerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fleetVehiclesControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fleetVehiclesControllerList>>,
          TError,
          Awaited<ReturnType<typeof fleetVehiclesControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFleetVehiclesControllerList<TData = Awaited<ReturnType<typeof fleetVehiclesControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fleetVehiclesControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fleetVehiclesControllerList>>,
          TError,
          Awaited<ReturnType<typeof fleetVehiclesControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFleetVehiclesControllerList<TData = Awaited<ReturnType<typeof fleetVehiclesControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fleetVehiclesControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFleetVehiclesControllerList<TData = Awaited<ReturnType<typeof fleetVehiclesControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fleetVehiclesControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFleetVehiclesControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getFleetVehiclesControllerCreateUrl = () => {




  return `/api/fleet-vehicles`
}

export const fleetVehiclesControllerCreate = async (createFleetVehicleDto: CreateFleetVehicleDto, options?: Parameters<typeof fetcher>[1]): Promise<FleetVehicleEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<FleetVehicleEntity>(getFleetVehiclesControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createFleetVehicleDto)
  }
);}





export const getFleetVehiclesControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerCreate>>, TError,FleetVehiclesControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerCreate>>, TError,FleetVehiclesControllerCreateMutationVariables, TContext> => {

const mutationKey = ['fleetVehiclesControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fleetVehiclesControllerCreate>>, FleetVehiclesControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  fleetVehiclesControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FleetVehiclesControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof fleetVehiclesControllerCreate>>>
    export type FleetVehiclesControllerCreateMutationBody = CreateFleetVehicleDto
    export type FleetVehiclesControllerCreateMutationError = unknown
    export type FleetVehiclesControllerCreateMutationVariables = {data: CreateFleetVehicleDto}

    export const useFleetVehiclesControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerCreate>>, TError,FleetVehiclesControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fleetVehiclesControllerCreate>>,
        TError,
        FleetVehiclesControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getFleetVehiclesControllerCreateMutationOptions(options), queryClient);
    }
    export const getFleetVehiclesControllerUpdateUrl = (ref: string,) => {




  return `/api/fleet-vehicles/${ref}`
}

export const fleetVehiclesControllerUpdate = async (ref: string,
    createFleetVehicleDto: CreateFleetVehicleDto, options?: Parameters<typeof fetcher>[1]): Promise<FleetVehicleEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<FleetVehicleEntity>(getFleetVehiclesControllerUpdateUrl(ref),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createFleetVehicleDto)
  }
);}





export const getFleetVehiclesControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerUpdate>>, TError,FleetVehiclesControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerUpdate>>, TError,FleetVehiclesControllerUpdateMutationVariables, TContext> => {

const mutationKey = ['fleetVehiclesControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fleetVehiclesControllerUpdate>>, FleetVehiclesControllerUpdateMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  fleetVehiclesControllerUpdate(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FleetVehiclesControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof fleetVehiclesControllerUpdate>>>
    export type FleetVehiclesControllerUpdateMutationBody = CreateFleetVehicleDto
    export type FleetVehiclesControllerUpdateMutationError = unknown
    export type FleetVehiclesControllerUpdateMutationVariables = {ref: string;data: CreateFleetVehicleDto}

    export const useFleetVehiclesControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerUpdate>>, TError,FleetVehiclesControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fleetVehiclesControllerUpdate>>,
        TError,
        FleetVehiclesControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getFleetVehiclesControllerUpdateMutationOptions(options), queryClient);
    }
    export const getFleetVehiclesControllerDeleteUrl = (ref: string,) => {




  return `/api/fleet-vehicles/${ref}`
}

export const fleetVehiclesControllerDelete = async (ref: string, options?: Parameters<typeof fetcher>[1]): Promise<OkResponseEntity> => {

  return fetcher<OkResponseEntity>(getFleetVehiclesControllerDeleteUrl(ref),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getFleetVehiclesControllerDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerDelete>>, TError,FleetVehiclesControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerDelete>>, TError,FleetVehiclesControllerDeleteMutationVariables, TContext> => {

const mutationKey = ['fleetVehiclesControllerDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fleetVehiclesControllerDelete>>, FleetVehiclesControllerDeleteMutationVariables> = (props) => {
          const {ref} = props ?? {};

          return  fleetVehiclesControllerDelete(ref,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FleetVehiclesControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof fleetVehiclesControllerDelete>>>

    export type FleetVehiclesControllerDeleteMutationError = unknown
    export type FleetVehiclesControllerDeleteMutationVariables = {ref: string}

    export const useFleetVehiclesControllerDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerDelete>>, TError,FleetVehiclesControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fleetVehiclesControllerDelete>>,
        TError,
        FleetVehiclesControllerDeleteMutationVariables,
        TContext
      > => {
      return useMutation(getFleetVehiclesControllerDeleteMutationOptions(options), queryClient);
    }
    export const getFleetVehiclesControllerSetActiveUrl = (ref: string,) => {




  return `/api/fleet-vehicles/${ref}/active`
}

export const fleetVehiclesControllerSetActive = async (ref: string,
    setActiveDto: SetActiveDto, options?: Parameters<typeof fetcher>[1]): Promise<FleetVehicleEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<FleetVehicleEntity>(getFleetVehiclesControllerSetActiveUrl(ref),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setActiveDto)
  }
);}





export const getFleetVehiclesControllerSetActiveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerSetActive>>, TError,FleetVehiclesControllerSetActiveMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerSetActive>>, TError,FleetVehiclesControllerSetActiveMutationVariables, TContext> => {

const mutationKey = ['fleetVehiclesControllerSetActive'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fleetVehiclesControllerSetActive>>, FleetVehiclesControllerSetActiveMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  fleetVehiclesControllerSetActive(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FleetVehiclesControllerSetActiveMutationResult = NonNullable<Awaited<ReturnType<typeof fleetVehiclesControllerSetActive>>>
    export type FleetVehiclesControllerSetActiveMutationBody = SetActiveDto
    export type FleetVehiclesControllerSetActiveMutationError = unknown
    export type FleetVehiclesControllerSetActiveMutationVariables = {ref: string;data: SetActiveDto}

    export const useFleetVehiclesControllerSetActive = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerSetActive>>, TError,FleetVehiclesControllerSetActiveMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fleetVehiclesControllerSetActive>>,
        TError,
        FleetVehiclesControllerSetActiveMutationVariables,
        TContext
      > => {
      return useMutation(getFleetVehiclesControllerSetActiveMutationOptions(options), queryClient);
    }
    export const getFleetVehiclesControllerSetDriverUrl = (ref: string,) => {




  return `/api/fleet-vehicles/${ref}/driver`
}

export const fleetVehiclesControllerSetDriver = async (ref: string,
    setFleetDriverDto: SetFleetDriverDto, options?: Parameters<typeof fetcher>[1]): Promise<FleetVehicleEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<FleetVehicleEntity>(getFleetVehiclesControllerSetDriverUrl(ref),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setFleetDriverDto)
  }
);}





export const getFleetVehiclesControllerSetDriverMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerSetDriver>>, TError,FleetVehiclesControllerSetDriverMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerSetDriver>>, TError,FleetVehiclesControllerSetDriverMutationVariables, TContext> => {

const mutationKey = ['fleetVehiclesControllerSetDriver'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fleetVehiclesControllerSetDriver>>, FleetVehiclesControllerSetDriverMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  fleetVehiclesControllerSetDriver(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FleetVehiclesControllerSetDriverMutationResult = NonNullable<Awaited<ReturnType<typeof fleetVehiclesControllerSetDriver>>>
    export type FleetVehiclesControllerSetDriverMutationBody = SetFleetDriverDto
    export type FleetVehiclesControllerSetDriverMutationError = unknown
    export type FleetVehiclesControllerSetDriverMutationVariables = {ref: string;data: SetFleetDriverDto}

    export const useFleetVehiclesControllerSetDriver = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerSetDriver>>, TError,FleetVehiclesControllerSetDriverMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fleetVehiclesControllerSetDriver>>,
        TError,
        FleetVehiclesControllerSetDriverMutationVariables,
        TContext
      > => {
      return useMutation(getFleetVehiclesControllerSetDriverMutationOptions(options), queryClient);
    }
    export const getFleetVehiclesControllerSetUnavailabilityUrl = (ref: string,) => {




  return `/api/fleet-vehicles/${ref}/unavailability`
}

export const fleetVehiclesControllerSetUnavailability = async (ref: string,
    setFleetUnavailabilityDto: SetFleetUnavailabilityDto, options?: Parameters<typeof fetcher>[1]): Promise<FleetVehicleEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<FleetVehicleEntity>(getFleetVehiclesControllerSetUnavailabilityUrl(ref),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setFleetUnavailabilityDto)
  }
);}





export const getFleetVehiclesControllerSetUnavailabilityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerSetUnavailability>>, TError,FleetVehiclesControllerSetUnavailabilityMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerSetUnavailability>>, TError,FleetVehiclesControllerSetUnavailabilityMutationVariables, TContext> => {

const mutationKey = ['fleetVehiclesControllerSetUnavailability'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fleetVehiclesControllerSetUnavailability>>, FleetVehiclesControllerSetUnavailabilityMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  fleetVehiclesControllerSetUnavailability(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FleetVehiclesControllerSetUnavailabilityMutationResult = NonNullable<Awaited<ReturnType<typeof fleetVehiclesControllerSetUnavailability>>>
    export type FleetVehiclesControllerSetUnavailabilityMutationBody = SetFleetUnavailabilityDto
    export type FleetVehiclesControllerSetUnavailabilityMutationError = unknown
    export type FleetVehiclesControllerSetUnavailabilityMutationVariables = {ref: string;data: SetFleetUnavailabilityDto}

    export const useFleetVehiclesControllerSetUnavailability = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fleetVehiclesControllerSetUnavailability>>, TError,FleetVehiclesControllerSetUnavailabilityMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fleetVehiclesControllerSetUnavailability>>,
        TError,
        FleetVehiclesControllerSetUnavailabilityMutationVariables,
        TContext
      > => {
      return useMutation(getFleetVehiclesControllerSetUnavailabilityMutationOptions(options), queryClient);
    }
