/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ClientEntity,
  ClientListEntity,
  ClientsControllerListParams,
  CreateClientDto,
  OkResponseEntity,
  ReactivateDto,
  ReactivateResponseEntity,
  ReactivationCandidatesEntity,
  SetActiveDto,
  UpdateClientDto
} from '../../model';

import { fetcher } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getClientsControllerListUrl = (params?: ClientsControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/clients?${stringifiedParams}` : `/api/clients`
}

export const clientsControllerList = async (params?: ClientsControllerListParams, options?: Parameters<typeof fetcher>[1]): Promise<ClientListEntity> => {

  return fetcher<ClientListEntity>(getClientsControllerListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getClientsControllerListQueryKey = (params?: ClientsControllerListParams,) => {
    return [
    `/api/clients`, ...(params ? [params] : [])
    ] as const;
    }


export const getClientsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof clientsControllerList>>, TError = unknown>(params?: ClientsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClientsControllerListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof clientsControllerList>>> = ({ signal }) => clientsControllerList(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof clientsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClientsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof clientsControllerList>>>
export type ClientsControllerListQueryError = unknown


export function useClientsControllerList<TData = Awaited<ReturnType<typeof clientsControllerList>>, TError = unknown>(
 params: undefined |  ClientsControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof clientsControllerList>>,
          TError,
          Awaited<ReturnType<typeof clientsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClientsControllerList<TData = Awaited<ReturnType<typeof clientsControllerList>>, TError = unknown>(
 params?: ClientsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof clientsControllerList>>,
          TError,
          Awaited<ReturnType<typeof clientsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClientsControllerList<TData = Awaited<ReturnType<typeof clientsControllerList>>, TError = unknown>(
 params?: ClientsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useClientsControllerList<TData = Awaited<ReturnType<typeof clientsControllerList>>, TError = unknown>(
 params?: ClientsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClientsControllerListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getClientsControllerCreateUrl = () => {




  return `/api/clients`
}

export const clientsControllerCreate = async (createClientDto: CreateClientDto, options?: Parameters<typeof fetcher>[1]): Promise<ClientEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<ClientEntity>(getClientsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createClientDto)
  }
);}





export const getClientsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerCreate>>, TError,ClientsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof clientsControllerCreate>>, TError,ClientsControllerCreateMutationVariables, TContext> => {

const mutationKey = ['clientsControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clientsControllerCreate>>, ClientsControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  clientsControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClientsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof clientsControllerCreate>>>
    export type ClientsControllerCreateMutationBody = CreateClientDto
    export type ClientsControllerCreateMutationError = unknown
    export type ClientsControllerCreateMutationVariables = {data: CreateClientDto}

    export const useClientsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerCreate>>, TError,ClientsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clientsControllerCreate>>,
        TError,
        ClientsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getClientsControllerCreateMutationOptions(options), queryClient);
    }
    export const getClientsControllerUpdateUrl = (ref: string,) => {




  return `/api/clients/${ref}`
}

export const clientsControllerUpdate = async (ref: string,
    updateClientDto: UpdateClientDto, options?: Parameters<typeof fetcher>[1]): Promise<ClientEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<ClientEntity>(getClientsControllerUpdateUrl(ref),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateClientDto)
  }
);}





export const getClientsControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerUpdate>>, TError,ClientsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof clientsControllerUpdate>>, TError,ClientsControllerUpdateMutationVariables, TContext> => {

const mutationKey = ['clientsControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clientsControllerUpdate>>, ClientsControllerUpdateMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  clientsControllerUpdate(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClientsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof clientsControllerUpdate>>>
    export type ClientsControllerUpdateMutationBody = UpdateClientDto
    export type ClientsControllerUpdateMutationError = unknown
    export type ClientsControllerUpdateMutationVariables = {ref: string;data: UpdateClientDto}

    export const useClientsControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerUpdate>>, TError,ClientsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clientsControllerUpdate>>,
        TError,
        ClientsControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getClientsControllerUpdateMutationOptions(options), queryClient);
    }
    export const getClientsControllerDeleteUrl = (ref: string,) => {




  return `/api/clients/${ref}`
}

export const clientsControllerDelete = async (ref: string, options?: Parameters<typeof fetcher>[1]): Promise<OkResponseEntity> => {

  return fetcher<OkResponseEntity>(getClientsControllerDeleteUrl(ref),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getClientsControllerDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerDelete>>, TError,ClientsControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof clientsControllerDelete>>, TError,ClientsControllerDeleteMutationVariables, TContext> => {

const mutationKey = ['clientsControllerDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clientsControllerDelete>>, ClientsControllerDeleteMutationVariables> = (props) => {
          const {ref} = props ?? {};

          return  clientsControllerDelete(ref,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClientsControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof clientsControllerDelete>>>

    export type ClientsControllerDeleteMutationError = unknown
    export type ClientsControllerDeleteMutationVariables = {ref: string}

    export const useClientsControllerDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerDelete>>, TError,ClientsControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clientsControllerDelete>>,
        TError,
        ClientsControllerDeleteMutationVariables,
        TContext
      > => {
      return useMutation(getClientsControllerDeleteMutationOptions(options), queryClient);
    }
    export const getClientsControllerSetActiveUrl = (ref: string,) => {




  return `/api/clients/${ref}/active`
}

export const clientsControllerSetActive = async (ref: string,
    setActiveDto: SetActiveDto, options?: Parameters<typeof fetcher>[1]): Promise<ClientEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<ClientEntity>(getClientsControllerSetActiveUrl(ref),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setActiveDto)
  }
);}





export const getClientsControllerSetActiveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerSetActive>>, TError,ClientsControllerSetActiveMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof clientsControllerSetActive>>, TError,ClientsControllerSetActiveMutationVariables, TContext> => {

const mutationKey = ['clientsControllerSetActive'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clientsControllerSetActive>>, ClientsControllerSetActiveMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  clientsControllerSetActive(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClientsControllerSetActiveMutationResult = NonNullable<Awaited<ReturnType<typeof clientsControllerSetActive>>>
    export type ClientsControllerSetActiveMutationBody = SetActiveDto
    export type ClientsControllerSetActiveMutationError = unknown
    export type ClientsControllerSetActiveMutationVariables = {ref: string;data: SetActiveDto}

    export const useClientsControllerSetActive = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerSetActive>>, TError,ClientsControllerSetActiveMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clientsControllerSetActive>>,
        TError,
        ClientsControllerSetActiveMutationVariables,
        TContext
      > => {
      return useMutation(getClientsControllerSetActiveMutationOptions(options), queryClient);
    }
    export const getClientsControllerListReactivationCandidatesUrl = (ref: string,) => {




  return `/api/clients/${ref}/reactivation-candidates`
}

export const clientsControllerListReactivationCandidates = async (ref: string, options?: Parameters<typeof fetcher>[1]): Promise<ReactivationCandidatesEntity> => {

  return fetcher<ReactivationCandidatesEntity>(getClientsControllerListReactivationCandidatesUrl(ref),
  {
    ...options,
    method: 'GET'


  }
);}





export const getClientsControllerListReactivationCandidatesQueryKey = (ref: string,) => {
    return [
    `/api/clients/${ref}/reactivation-candidates`
    ] as const;
    }


export const getClientsControllerListReactivationCandidatesQueryOptions = <TData = Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>, TError = unknown>(ref: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClientsControllerListReactivationCandidatesQueryKey(ref);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>> = ({ signal }) => clientsControllerListReactivationCandidates(ref, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: ref !== null && ref !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClientsControllerListReactivationCandidatesQueryResult = NonNullable<Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>>
export type ClientsControllerListReactivationCandidatesQueryError = unknown


export function useClientsControllerListReactivationCandidates<TData = Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>, TError = unknown>(
 ref: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>,
          TError,
          Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClientsControllerListReactivationCandidates<TData = Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>, TError = unknown>(
 ref: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>,
          TError,
          Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClientsControllerListReactivationCandidates<TData = Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>, TError = unknown>(
 ref: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useClientsControllerListReactivationCandidates<TData = Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>, TError = unknown>(
 ref: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerListReactivationCandidates>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClientsControllerListReactivationCandidatesQueryOptions(ref,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getClientsControllerReactivateUrl = (ref: string,) => {




  return `/api/clients/${ref}/reactivate`
}

export const clientsControllerReactivate = async (ref: string,
    reactivateDto: ReactivateDto, options?: Parameters<typeof fetcher>[1]): Promise<ReactivateResponseEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<ReactivateResponseEntity>(getClientsControllerReactivateUrl(ref),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(reactivateDto)
  }
);}





export const getClientsControllerReactivateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerReactivate>>, TError,ClientsControllerReactivateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof clientsControllerReactivate>>, TError,ClientsControllerReactivateMutationVariables, TContext> => {

const mutationKey = ['clientsControllerReactivate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clientsControllerReactivate>>, ClientsControllerReactivateMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  clientsControllerReactivate(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClientsControllerReactivateMutationResult = NonNullable<Awaited<ReturnType<typeof clientsControllerReactivate>>>
    export type ClientsControllerReactivateMutationBody = ReactivateDto
    export type ClientsControllerReactivateMutationError = unknown
    export type ClientsControllerReactivateMutationVariables = {ref: string;data: ReactivateDto}

    export const useClientsControllerReactivate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerReactivate>>, TError,ClientsControllerReactivateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clientsControllerReactivate>>,
        TError,
        ClientsControllerReactivateMutationVariables,
        TContext
      > => {
      return useMutation(getClientsControllerReactivateMutationOptions(options), queryClient);
    }
