/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompanyInfoEntity,
  UpdateCompanyInfoDto
} from '../../model';

import { fetcher } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getCompanyControllerGetUrl = () => {




  return `/api/company-info`
}

export const companyControllerGet = async ( options?: Parameters<typeof fetcher>[1]): Promise<CompanyInfoEntity> => {

  return fetcher<CompanyInfoEntity>(getCompanyControllerGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getCompanyControllerGetQueryKey = () => {
    return [
    `/api/company-info`
    ] as const;
    }


export const getCompanyControllerGetQueryOptions = <TData = Awaited<ReturnType<typeof companyControllerGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyControllerGet>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompanyControllerGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof companyControllerGet>>> = ({ signal }) => companyControllerGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof companyControllerGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompanyControllerGetQueryResult = NonNullable<Awaited<ReturnType<typeof companyControllerGet>>>
export type CompanyControllerGetQueryError = unknown


export function useCompanyControllerGet<TData = Awaited<ReturnType<typeof companyControllerGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyControllerGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerGet>>,
          TError,
          Awaited<ReturnType<typeof companyControllerGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompanyControllerGet<TData = Awaited<ReturnType<typeof companyControllerGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyControllerGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerGet>>,
          TError,
          Awaited<ReturnType<typeof companyControllerGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompanyControllerGet<TData = Awaited<ReturnType<typeof companyControllerGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyControllerGet>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCompanyControllerGet<TData = Awaited<ReturnType<typeof companyControllerGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof companyControllerGet>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompanyControllerGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getCompanyControllerUpdateUrl = () => {




  return `/api/company-info`
}

export const companyControllerUpdate = async (updateCompanyInfoDto: UpdateCompanyInfoDto, options?: Parameters<typeof fetcher>[1]): Promise<CompanyInfoEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<CompanyInfoEntity>(getCompanyControllerUpdateUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateCompanyInfoDto)
  }
);}





export const getCompanyControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof companyControllerUpdate>>, TError,CompanyControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof companyControllerUpdate>>, TError,CompanyControllerUpdateMutationVariables, TContext> => {

const mutationKey = ['companyControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof companyControllerUpdate>>, CompanyControllerUpdateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  companyControllerUpdate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompanyControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof companyControllerUpdate>>>
    export type CompanyControllerUpdateMutationBody = UpdateCompanyInfoDto
    export type CompanyControllerUpdateMutationError = unknown
    export type CompanyControllerUpdateMutationVariables = {data: UpdateCompanyInfoDto}

    export const useCompanyControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof companyControllerUpdate>>, TError,CompanyControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof companyControllerUpdate>>,
        TError,
        CompanyControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getCompanyControllerUpdateMutationOptions(options), queryClient);
    }
