/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateDriverDto,
  DriverEntity,
  DriverWithUnavailabilityEntity,
  OkResponseEntity,
  SetActiveDto,
  SetDriverUnavailabilityDto
} from '../../model';

import { fetcher } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getDriversControllerListUrl = () => {




  return `/api/drivers`
}

export const driversControllerList = async ( options?: Parameters<typeof fetcher>[1]): Promise<DriverEntity[]> => {

  return fetcher<DriverEntity[]>(getDriversControllerListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getDriversControllerListQueryKey = () => {
    return [
    `/api/drivers`
    ] as const;
    }


export const getDriversControllerListQueryOptions = <TData = Awaited<ReturnType<typeof driversControllerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof driversControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDriversControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof driversControllerList>>> = ({ signal }) => driversControllerList({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof driversControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DriversControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof driversControllerList>>>
export type DriversControllerListQueryError = unknown


export function useDriversControllerList<TData = Awaited<ReturnType<typeof driversControllerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof driversControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof driversControllerList>>,
          TError,
          Awaited<ReturnType<typeof driversControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDriversControllerList<TData = Awaited<ReturnType<typeof driversControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof driversControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof driversControllerList>>,
          TError,
          Awaited<ReturnType<typeof driversControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDriversControllerList<TData = Awaited<ReturnType<typeof driversControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof driversControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDriversControllerList<TData = Awaited<ReturnType<typeof driversControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof driversControllerList>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDriversControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getDriversControllerCreateUrl = () => {




  return `/api/drivers`
}

export const driversControllerCreate = async (createDriverDto: CreateDriverDto, options?: Parameters<typeof fetcher>[1]): Promise<DriverEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<DriverEntity>(getDriversControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createDriverDto)
  }
);}





export const getDriversControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof driversControllerCreate>>, TError,DriversControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof driversControllerCreate>>, TError,DriversControllerCreateMutationVariables, TContext> => {

const mutationKey = ['driversControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof driversControllerCreate>>, DriversControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  driversControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DriversControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof driversControllerCreate>>>
    export type DriversControllerCreateMutationBody = CreateDriverDto
    export type DriversControllerCreateMutationError = unknown
    export type DriversControllerCreateMutationVariables = {data: CreateDriverDto}

    export const useDriversControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof driversControllerCreate>>, TError,DriversControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof driversControllerCreate>>,
        TError,
        DriversControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getDriversControllerCreateMutationOptions(options), queryClient);
    }
    export const getDriversControllerUpdateUrl = (ref: string,) => {




  return `/api/drivers/${ref}`
}

export const driversControllerUpdate = async (ref: string,
    createDriverDto: CreateDriverDto, options?: Parameters<typeof fetcher>[1]): Promise<DriverEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<DriverEntity>(getDriversControllerUpdateUrl(ref),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createDriverDto)
  }
);}





export const getDriversControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof driversControllerUpdate>>, TError,DriversControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof driversControllerUpdate>>, TError,DriversControllerUpdateMutationVariables, TContext> => {

const mutationKey = ['driversControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof driversControllerUpdate>>, DriversControllerUpdateMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  driversControllerUpdate(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DriversControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof driversControllerUpdate>>>
    export type DriversControllerUpdateMutationBody = CreateDriverDto
    export type DriversControllerUpdateMutationError = unknown
    export type DriversControllerUpdateMutationVariables = {ref: string;data: CreateDriverDto}

    export const useDriversControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof driversControllerUpdate>>, TError,DriversControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof driversControllerUpdate>>,
        TError,
        DriversControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getDriversControllerUpdateMutationOptions(options), queryClient);
    }
    export const getDriversControllerDeleteUrl = (ref: string,) => {




  return `/api/drivers/${ref}`
}

export const driversControllerDelete = async (ref: string, options?: Parameters<typeof fetcher>[1]): Promise<OkResponseEntity> => {

  return fetcher<OkResponseEntity>(getDriversControllerDeleteUrl(ref),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDriversControllerDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof driversControllerDelete>>, TError,DriversControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof driversControllerDelete>>, TError,DriversControllerDeleteMutationVariables, TContext> => {

const mutationKey = ['driversControllerDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof driversControllerDelete>>, DriversControllerDeleteMutationVariables> = (props) => {
          const {ref} = props ?? {};

          return  driversControllerDelete(ref,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DriversControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof driversControllerDelete>>>

    export type DriversControllerDeleteMutationError = unknown
    export type DriversControllerDeleteMutationVariables = {ref: string}

    export const useDriversControllerDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof driversControllerDelete>>, TError,DriversControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof driversControllerDelete>>,
        TError,
        DriversControllerDeleteMutationVariables,
        TContext
      > => {
      return useMutation(getDriversControllerDeleteMutationOptions(options), queryClient);
    }
    export const getDriversControllerSetActiveUrl = (ref: string,) => {




  return `/api/drivers/${ref}/active`
}

export const driversControllerSetActive = async (ref: string,
    setActiveDto: SetActiveDto, options?: Parameters<typeof fetcher>[1]): Promise<DriverEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<DriverEntity>(getDriversControllerSetActiveUrl(ref),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setActiveDto)
  }
);}





export const getDriversControllerSetActiveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof driversControllerSetActive>>, TError,DriversControllerSetActiveMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof driversControllerSetActive>>, TError,DriversControllerSetActiveMutationVariables, TContext> => {

const mutationKey = ['driversControllerSetActive'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof driversControllerSetActive>>, DriversControllerSetActiveMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  driversControllerSetActive(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DriversControllerSetActiveMutationResult = NonNullable<Awaited<ReturnType<typeof driversControllerSetActive>>>
    export type DriversControllerSetActiveMutationBody = SetActiveDto
    export type DriversControllerSetActiveMutationError = unknown
    export type DriversControllerSetActiveMutationVariables = {ref: string;data: SetActiveDto}

    export const useDriversControllerSetActive = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof driversControllerSetActive>>, TError,DriversControllerSetActiveMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof driversControllerSetActive>>,
        TError,
        DriversControllerSetActiveMutationVariables,
        TContext
      > => {
      return useMutation(getDriversControllerSetActiveMutationOptions(options), queryClient);
    }
    export const getDriversControllerSetUnavailabilityUrl = (ref: string,) => {




  return `/api/drivers/${ref}/unavailability`
}

export const driversControllerSetUnavailability = async (ref: string,
    setDriverUnavailabilityDto: SetDriverUnavailabilityDto, options?: Parameters<typeof fetcher>[1]): Promise<DriverWithUnavailabilityEntity> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return fetcher<DriverWithUnavailabilityEntity>(getDriversControllerSetUnavailabilityUrl(ref),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setDriverUnavailabilityDto)
  }
);}





export const getDriversControllerSetUnavailabilityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof driversControllerSetUnavailability>>, TError,DriversControllerSetUnavailabilityMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof driversControllerSetUnavailability>>, TError,DriversControllerSetUnavailabilityMutationVariables, TContext> => {

const mutationKey = ['driversControllerSetUnavailability'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof driversControllerSetUnavailability>>, DriversControllerSetUnavailabilityMutationVariables> = (props) => {
          const {ref,data} = props ?? {};

          return  driversControllerSetUnavailability(ref,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DriversControllerSetUnavailabilityMutationResult = NonNullable<Awaited<ReturnType<typeof driversControllerSetUnavailability>>>
    export type DriversControllerSetUnavailabilityMutationBody = SetDriverUnavailabilityDto
    export type DriversControllerSetUnavailabilityMutationError = unknown
    export type DriversControllerSetUnavailabilityMutationVariables = {ref: string;data: SetDriverUnavailabilityDto}

    export const useDriversControllerSetUnavailability = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof driversControllerSetUnavailability>>, TError,DriversControllerSetUnavailabilityMutationVariables, TContext>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof driversControllerSetUnavailability>>,
        TError,
        DriversControllerSetUnavailabilityMutationVariables,
        TContext
      > => {
      return useMutation(getDriversControllerSetUnavailabilityMutationOptions(options), queryClient);
    }
