/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Cockpit API
 * Cockpit v2 dispatch/booking API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MetaEntity
} from '../../model';

import { fetcher } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getMetaControllerGetMetaUrl = () => {




  return `/api/meta`
}

export const metaControllerGetMeta = async ( options?: Parameters<typeof fetcher>[1]): Promise<MetaEntity> => {

  return fetcher<MetaEntity>(getMetaControllerGetMetaUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getMetaControllerGetMetaQueryKey = () => {
    return [
    `/api/meta`
    ] as const;
    }


export const getMetaControllerGetMetaQueryOptions = <TData = Awaited<ReturnType<typeof metaControllerGetMeta>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof metaControllerGetMeta>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMetaControllerGetMetaQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof metaControllerGetMeta>>> = ({ signal }) => metaControllerGetMeta({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof metaControllerGetMeta>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MetaControllerGetMetaQueryResult = NonNullable<Awaited<ReturnType<typeof metaControllerGetMeta>>>
export type MetaControllerGetMetaQueryError = unknown


export function useMetaControllerGetMeta<TData = Awaited<ReturnType<typeof metaControllerGetMeta>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof metaControllerGetMeta>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof metaControllerGetMeta>>,
          TError,
          Awaited<ReturnType<typeof metaControllerGetMeta>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMetaControllerGetMeta<TData = Awaited<ReturnType<typeof metaControllerGetMeta>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof metaControllerGetMeta>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof metaControllerGetMeta>>,
          TError,
          Awaited<ReturnType<typeof metaControllerGetMeta>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMetaControllerGetMeta<TData = Awaited<ReturnType<typeof metaControllerGetMeta>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof metaControllerGetMeta>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMetaControllerGetMeta<TData = Awaited<ReturnType<typeof metaControllerGetMeta>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof metaControllerGetMeta>>, TError, TData>>, request?: SecondParameter<typeof fetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMetaControllerGetMetaQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






